// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Receipt for a newly started background session: the short job id usable
 * with `claude attach/logs/stop` and the attach WebSocket.
 */
export type AgentSpawned = { id: string, };
