// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two kinds of work an [`AgentChild`] is. Exactly two: a
 * subagent (a sidechain transcript, no process of its own) and a shell (one
 * `/bin/zsh -c …` child, i.e. a Bash tool call in flight).
 */
export type AgentChildKind = "subagent" | "shell";
