// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Receipt for a newly started background session: the short job id usable
 * with `claude attach/logs/stop` and the attach WebSocket.
 *
 * `null` when the spawn command printed no `backgrounded · <id>` receipt —
 * possible since the command is user-configurable (`core::config`), and not
 * an error: the session started, mesa just can't pre-open an attach pane for
 * it. Clients must treat a null id as "created, discover it in the session
 * list", never as a failure.
 */
export type AgentSpawned = { id: string | null, };
