// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One live Claude Code session as reported by `claude agents --json`.
 * Parsed from that external CLI output and re-served to the web UI verbatim,
 * so field names stay camelCase end to end (serde renames both directions).
 */
export type AgentSession = { 
/**
 * OS process id; absent once the session's process has exited.
 */
pid: number | null, 
/**
 * Short job id (`claude attach <id>`); background sessions only, so this
 * is also the "attachable" marker.
 */
id: string | null, cwd: string, 
/**
 * `background` (started with `--bg`, attachable) or `interactive`
 * (someone's own terminal — listed, but not attachable).
 */
kind: string, 
/**
 * Session start, milliseconds since epoch.
 */
startedAt: number, sessionId: string, name: string | null, 
/**
 * e.g. `busy` | `idle`; absent once the process has exited.
 */
status: string | null, 
/**
 * e.g. `working` | `blocked` | `done` | `failed` | `stopped`.
 */
state: string | null, 
/**
 * What a blocked session is waiting on (e.g. "permission prompt").
 */
waitingFor: string | null, };
