// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentChildKind } from "./AgentChildKind";
import type { AgentChildState } from "./AgentChildState";

/**
 * One piece of work hanging off a live session (mesa task 1277) — a subagent
 * or a shell — as the Agents panel's child cards show it.
 *
 * Every field but `kind`/`name`/`state` is optional because each is a
 * best-effort read of something outside mesa (a transcript tail, a `ps`
 * row): an unreadable file yields a child with what is known rather than no
 * child at all.
 */
export type AgentChild = { kind: AgentChildKind, 
/**
 * A subagent's `agentType` (from the transcript's `.meta.json` sidecar,
 * falling back to the file stem), or a shell's command line. Bounded by
 * `cc::sanitize_capped` like every other string mesa lifts out of an
 * external file — untrusted text on a poll.
 */
name: string, 
/**
 * The last thing a subagent did: its newest assistant prose, else the
 * tool that message called. `None` for a shell — a Bash call in flight
 * has produced no output yet — and for a subagent that has said nothing.
 */
detail: string | null, 
/**
 * When this child started, as mesa's own stored timestamp text
 * (`YYYY-MM-DD HH:MM:SS`, UTC) so the page parses it exactly as it parses
 * a db timestamp. `None` when neither the transcript nor `ps` says.
 */
startedAt: string | null, 
/**
 * A subagent's occupied context window, the same
 * `input + cache_read + cache_creation` figure a session's own
 * `context_tokens` is. Always `None` for a shell.
 */
contextTokens: number | null, state: AgentChildState, };
