// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an [`AgentChild`] is still working. A shell is only ever
 * `Running` — it disappears from `ps` the moment it returns — while a
 * subagent that has handed back its report reads `Finished` and lingers
 * until its transcript falls out of the `cc::ACTIVE_SECS` window, exactly as
 * the live count already behaves.
 */
export type AgentChildState = "running" | "finished";
