// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of a frame a `FrameEdge` endpoint is locked to, when locked at
 * all. Shares its four lowercase string values with React Flow's own
 * `Position` enum, so a value read off `FrameEdge.from_anchor`/`to_anchor`
 * casts directly into a `Position` prop with no translation table.
 */
export type AnchorSide = "top" | "right" | "bottom" | "left";
