// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an archived item was *disposed of* (mesa task 1248) — the enumerated
 * twin of `archive_reason`, which says it in prose. Four fixed answers, so a
 * reader can count them and an agent can be told which one to write:
 * **report** (an item addressed to a person, nothing to do), **duplicate**
 * (the work is already named somewhere else), **not-actionable** (the request
 * cannot be acted on as written) and **converted-to-task** (the work now
 * lives as a task). Nullable — an archive may still say nothing at all — and
 * so there is no `Default`.
 */
export type ArchiveOutcome = "report" | "duplicate" | "not-actionable" | "converted-to-task";
