// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent-written page bound to a project: a small text document — HTML
 * mockup, SVG diagram, or markdown page — rendered on the project's
 * Artifacts tab. The body lives in the db (unlike an [`Attachment`], which
 * is an arbitrary binary on disk): an artifact is closer in kind to a task
 * `description` or a diagram frame `body`, both already stored this way,
 * and keeping it there means one `mesa backup` story rather than a second
 * on-disk tree for `Store` to reconcile. `ARTIFACT_BODY_MAX` (`Store`) is
 * the hard cap that keeps this from becoming the attachment case by the
 * back door.
 */
export type Artifact = { id: number, 
/**
 * The project this artifact belongs to; immutable after creation (the
 * id is in the artifact's own URL). `ON DELETE CASCADE` — an artifact is
 * a page *about* a project and has nowhere to live without one.
 */
project_id: number, 
/**
 * The task that prompted this page, if any. `ON DELETE SET NULL` —
 * deleting the task that prompted a page must not destroy the page.
 */
task_id: number | null, 
/**
 * Unique (case-insensitively) within the project; the CLI resolves an
 * artifact by id only (unlike a script or project), but the name is
 * still the selector a person reads.
 */
name: string, 
/**
 * One of [`ARTIFACT_CONTENT_TYPES`].
 */
content_type: string, 
/**
 * The document itself, stored verbatim. Required, non-empty, capped at
 * `ARTIFACT_BODY_MAX` (`Store`) — unlike the live surface's
 * `LIVE_TEXT_MAX`, which does not apply here: an artifact is read, never
 * spoken.
 */
body: string, created_at: string, updated_at: string, };
