// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The API's `GET /api/projects/{id}/artifacts` list projection — every
 * [`Artifact`] field except `body` — the twin of the CLI's `QUIET_DROP_ARTIFACT`
 * compact shape (`src/cli.rs`); the two must stay in step, so a new bounded
 * field on `Artifact` belongs in both. Dropped for the same reason
 * [`TaskSummary`] drops `description`: `body` is a document capped at 2 MiB
 * (`Store::ARTIFACT_BODY_MAX`), and the primary caller of `list` is an agent
 * asking what pages exist in a project, not fetching every page's markup —
 * a project with many artifacts would otherwise return tens of megabytes
 * into a browser's memory for a question that only needed names and ids.
 */
export type ArtifactSummary = { id: number, project_id: number, task_id: number | null, name: string, content_type: string, created_at: string, updated_at: string, };
