// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file attached to a task. Bytes live on disk (see `core::attachments`),
 * derived from `(task_id, id, filename)` — never a path column to keep in
 * sync. Content bytes never appear in this type (spec req. 21); fetch them
 * via `Store::attachment_bytes`.
 */
export type Attachment = { id: number, task_id: number, filename: string, 
/**
 * Best-effort extension-based guess; `None` when unrecognized.
 */
content_type: string | null, size_bytes: number, 
/**
 * Free-text attribution of who attached the file.
 */
author: string | null, 
/**
 * When the file was attached (SQLite `datetime` text, UTC).
 */
created_at: string, };
