// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the probe found (design §4.4). Serialized snake_case — the exact
 * strings `GET /api/live/transcribe` answers with.
 */
export type AudioState = "ready" | "daemon_down" | "model_missing" | "incompatible" | "error";
