// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * Usage rolled up by `attributionAgent` (subagents).
 */
export type CcAgentStat = { agent: string, messages: number, sessions: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, };
