// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcChatOption } from "./CcChatOption";

/**
 * One question of a [`CcChatAsk`].
 */
export type CcChatQuestion = { 
/**
 * The question itself, bounded (`sanitize_capped`) like every other
 * transcript-derived label: this is model-authored text on a button.
 */
question: string, 
/**
 * The short chip the tool asks for beside it; empty when it carried none.
 */
header: string, 
/**
 * Whether the chooser takes more than one answer.
 */
multi_select: boolean, 
/**
 * The offered answers, in order. The tool's own `preview` is deliberately
 * dropped: it is unbounded and this payload is a 3s poll.
 */
options: Array<CcChatOption>, };
