// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcChatQuestion } from "./CcChatQuestion";

/**
 * The `AskUserQuestion` call a session is blocked on — see
 * [`CcSessionChat::pending_question`].
 */
export type CcChatAsk = { 
/**
 * The `tool_use_id` of the call. Also the id of the `tool` turn it
 * appears as in `turns`, so a client can tell the two apart across polls
 * — a *second* question is a different id, and answering the first one
 * makes this whole field `None`.
 */
id: string, 
/**
 * The questions of that one call, in the order the agent asked them —
 * which is also the order its own chooser walks them in.
 */
questions: Array<CcChatQuestion>, };
