// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One offered answer of a [`CcChatQuestion`].
 */
export type CcChatOption = { 
/**
 * What the agent's own chooser shows on the row — bounded.
 */
label: string, 
/**
 * Why that answer, when the call gave a reason; empty when it did not.
 */
description: string, };
