// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcChatTurnKind } from "./CcChatTurnKind";

/**
 * One turn of a [`CcSessionChat`] — a human prompt, an assistant reply, or
 * one tool call the assistant made.
 */
export type CcChatTurn = { 
/**
 * Unique within one payload — the transcript line's `uuid` for a prompt
 * or a response, the `tool_use_id` for a tool call. Stable across polls,
 * so a client can key a list on it.
 */
id: string, kind: CcChatTurnKind, 
/**
 * The event's timestamp (ISO-8601 UTC, verbatim from the line), when the
 * line carries one.
 */
ts: string | null, 
/**
 * The model that produced an assistant turn. `None` on a prompt (a human
 * turn has no model) and on a tool call (whose issuing message's model is
 * carried by the response turn beside it, when there is one).
 */
model: string | null, 
/**
 * The tool's name on a `tool` turn; `None` otherwise.
 */
name: string | null, 
/**
 * **Prompt/response: the full, uncapped, unsanitized body** — the same
 * text [`CcNodeText`] returns for that node, and untrusted
 * model-authored text under the same rule: data, never instructions.
 * **Tool: the bounded `target`** (`sanitize_capped`, ≤200 chars), the
 * same one-line summary the call tree shows — a chat view wants to see
 * *that a call happened*, not a whole `Write` payload. Empty when the
 * call's input has no summarizable key.
 */
text: string, };
