// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * One day's totals (the daily activity series).
 */
export type CcDayPoint = { 
/**
 * `YYYY-MM-DD` (UTC).
 */
date: string, sessions: number, messages: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, };
