// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcAgentStat } from "./CcAgentStat";
import type { CcDayPoint } from "./CcDayPoint";
import type { CcModelStat } from "./CcModelStat";
import type { CcOverview } from "./CcOverview";
import type { CcProjectStat } from "./CcProjectStat";
import type { CcSessionRow } from "./CcSessionRow";
import type { CcSkillStat } from "./CcSkillStat";

/**
 * The full CC dashboard payload returned by `mesa cc summary` and `GET /api/cc`.
 */
export type CcDashboard = { 
/**
 * Unix seconds at which this snapshot was computed.
 */
generated_at_unix: number, 
/**
 * The requested window token (`7d`/`30d`/`90d`/`all`/`<n>d`).
 */
window: string, 
/**
 * Inclusive cutoff date (`YYYY-MM-DD`), or null for `all`.
 */
since: string | null, overview: CcOverview, daily: Array<CcDayPoint>, models: Array<CcModelStat>, skills: Array<CcSkillStat>, agents: Array<CcAgentStat>, projects: Array<CcProjectStat>, 
/**
 * Sessions newest-first, capped (see `core::cc`); `overview.sessions` holds
 * the true total.
 */
sessions: Array<CcSessionRow>, };
