// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which mechanism refused a call. Two of them, deliberately never merged:
 * one is the user's own configuration, the other is Claude Code's.
 */
export type CcDenialKind = "hook" | "classifier";
