// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failures rolled up by the normalized head of a `Bash` command.
 */
export type CcErrorCommandStat = { prefix: string, errors: number, sidechain: number, top_level: number, };
