// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The window's failures in total. `sidechain + top_level == errors`;
 * `denials` is a subset of `errors`, not a fourth split.
 */
export type CcErrorTotals = { errors: number, sidechain: number, top_level: number, denials: number, };
