// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failures rolled up by their normalized message signature
 * (`core::cc::failure_signature`).
 */
export type CcErrorMessageStat = { 
/**
 * The first meaningful line of what the tool said, with paths, globs,
 * hex runs and digits masked. Untrusted text, sanitized and capped at
 * ingest like every other stored transcript-derived string.
 */
signature: string, errors: number, sidechain: number, top_level: number, 
/**
 * The distinct sessions that contributed to this row, sorted and capped
 * (`core::cc::ERROR_SESSION_LIMIT`) — where to go and read the failure,
 * which the counts alone never say. The counts count every session
 * regardless.
 */
sessions: Array<string>, };
