// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcDenialKind } from "./CcDenialKind";

/**
 * One `(kind, reason)` a refusal mechanism gave, and how often.
 *
 * Grouped on the **reason**, deliberately not on the command and not on the
 * tool. Both were tried against the real corpus and both fragment a
 * recurring rule into rows of one: the same hook fires from unrelated
 * command lines (`git push` is one clause of a longer one), and the same
 * classifier verdict blocks `Bash`, `Edit`, `Agent` and `Write` alike. What
 * varied is reported alongside instead, so nothing is lost.
 *
 * `kind` **is** in the key: a hook is the user's own configuration and the
 * classifier is Claude Code's, so a shared reason string would still be two
 * different facts.
 */
export type CcErrorDenial = { kind: CcDenialKind, 
/**
 * What the refusal said, sanitized and capped like every stored
 * transcript-derived string.
 */
reason: string, 
/**
 * The distinct normalized command heads seen under this reason, sorted
 * and capped (`core::cc::DENIAL_PREFIX_LIMIT`) — the hook's own named
 * command where it gave one, else the containing call's. Empty when
 * neither is known. `count` counts every refusal regardless.
 */
command_prefixes: Array<string>, 
/**
 * The distinct tools refused under this reason, sorted and capped the
 * same way — the tool the hook named, else the joined call row's. A
 * classifier verdict names no tool of its own, so for those this is
 * entirely the call row's.
 */
tools: Array<string>, count: number, };
