// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcErrorCommandStat } from "./CcErrorCommandStat";
import type { CcErrorDenial } from "./CcErrorDenial";
import type { CcErrorMessageStat } from "./CcErrorMessageStat";
import type { CcErrorToolStat } from "./CcErrorToolStat";
import type { CcErrorTotals } from "./CcErrorTotals";

/**
 * What failed, over a window — `mesa cc errors`.
 *
 * One object rather than a bare array because there are three groupings of
 * one population, and every count is split sidechain vs. top level: over half
 * of all failures are a subagent's, so a single number answers neither "is my
 * own work going wrong" nor "are my agents".
 */
export type CcErrors = { 
/**
 * Unix seconds at which this snapshot was computed.
 */
generated_at_unix: number, 
/**
 * The requested window token, as `CcDashboard::window`.
 */
window: string, 
/**
 * Inclusive cutoff date (`YYYY-MM-DD`), or null for `all`.
 */
since: string | null, 
/**
 * The session the caller narrowed to (`mesa cc errors --session`, mesa
 * task 1255), echoed back; null when the view is every session.
 */
session: string | null, total: CcErrorTotals, 
/**
 * Most failures first. `name` is `unknown` for an error whose own
 * `tool_use` line has not been ingested.
 */
by_tool: Array<CcErrorToolStat>, 
/**
 * `Bash` only, most failures first — the normalized head of the command
 * (see `core::cc::command_prefix`), since over 90% of all failures are Bash
 * and the tool name alone says nothing about which of them.
 */
by_command: Array<CcErrorCommandStat>, 
/**
 * What the failures actually *said*, most failures first and capped at
 * `core::cc::MESSAGE_GROUP_LIMIT` — the only grouping that answers
 * **why** rather than what. `by_tool` and `by_command` name the thing
 * that failed; a recurring cause is spread across several commands and
 * visible in none of them.
 */
by_message: Array<CcErrorMessageStat>, 
/**
 * Calls a `PreToolUse` hook refused, most refusals first. A different
 * population from the rest: nothing ran.
 */
denials: Array<CcErrorDenial>, };
