// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failures rolled up by tool name.
 */
export type CcErrorToolStat = { name: string, errors: number, sidechain: number, top_level: number, 
/**
 * The distinct sessions that contributed to this row, sorted and capped
 * (`core::cc::ERROR_SESSION_LIMIT`) — where to go and read the failure,
 * which the counts alone never say. The counts count every session
 * regardless.
 */
sessions: Array<string>, };
