// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Failures rolled up by tool name.
 */
export type CcErrorToolStat = { name: string, errors: number, sidechain: number, top_level: number, };
