// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcGraphNodeKind } from "./CcGraphNodeKind";
import type { CcTokens } from "./CcTokens";

/**
 * One node of a session's call tree.
 *
 * **`tokens`/`total_tokens` mean different things per `kind`, and only
 * `tokens_are_rollup` distinguishes them.** On a `session` or `agent` node
 * they are that thread's own summed usage. On a `tool` node they are the
 * usage of the assistant message that *issued* the call — a message may emit
 * several `tool_use` blocks, so sibling tool nodes then repeat one message's
 * usage and **tool-node tokens must never be summed**.
 */
export type CcGraphNode = { 
/**
 * Stable within one graph, and namespaced by kind so a `tool_use_id` can
 * never collide with an `agent_id`: `"session"`, `"agent:<agent_id>"`,
 * `"tool:<tool_use_id>"`.
 */
id: string, kind: CcGraphNodeKind, 
/**
 * Tool name, subagent name, or the session's short id.
 */
name: string, 
/**
 * The issuing message's model (`tool`), or the thread's most-used model
 * (`session`/`agent`). `None` when no usage-carrying message backs it.
 */
model: string | null, tokens: CcTokens, total_tokens: number, 
/**
 * True when `tokens` is this node's own rolled-up usage (`session`,
 * `agent`); false on a `tool` node — see the type-level note.
 */
tokens_are_rollup: boolean, est_cost_usd: number, 
/**
 * First event timestamp (ISO-8601 UTC), when known.
 */
ts: string | null, 
/**
 * `agent` only: the run's attributed skill.
 */
skill: string | null, 
/**
 * `agent` only: the spawning call's one-line description (sidecar).
 */
description: string | null, 
/**
 * `agent` only: 1 for a main-thread spawn, 2+ when nested (sidecar).
 */
spawn_depth: number | null, 
/**
 * `session`/`agent` only: usage-carrying messages in that thread.
 */
messages: number, 
/**
 * `session`/`agent` only: tool calls made directly by that thread.
 */
tool_calls: number, 
/**
 * `tool` only: the `tool_use.caller`, verbatim.
 */
caller: string | null, };
