// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parent→child edge in the call tree: session→tool, tool→agent (the
 * spawning `Task` call), agent→tool.
 */
export type CcGraphEdge = { from: string, to: string, };
