// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one [`CcGraphNode`] stands for.
 */
export type CcGraphNodeKind = "session" | "agent" | "skill" | "tool" | "response" | "prompt";
