// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One closed stretch of wall-clock time, both ends ISO-8601 UTC — the same
 * form [`CcSessionThreadStat::start`]/`end` take.
 */
export type CcInterval = { start: string, end: string, };
