// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcLiveSession } from "./CcLiveSession";

/**
 * The live-sessions payload (`mesa cc live` / `GET /api/cc/live`): the slice of
 * the CC dashboard restricted to sessions active in the last `window_minutes`.
 * Cheap to compute (skips files whose mtime predates the window) so the UI can
 * poll it on a short interval for a near-real-time view.
 */
export type CcLive = { 
/**
 * Unix seconds at which this snapshot was computed.
 */
generated_at_unix: number, 
/**
 * Recency window: a session is "live" if its newest event is within this.
 */
window_minutes: number, 
/**
 * Width of each `spark` bucket, in seconds.
 */
bucket_seconds: number, 
/**
 * A session counts as `active` (vs merely `idle`/live) within this gap.
 */
active_seconds: number, 
/**
 * Sessions with an event in the active gap.
 */
active_count: number, 
/**
 * Total live sessions (== `sessions.len()`).
 */
live_count: number, 
/**
 * Tokens across all live sessions within the window.
 */
total_tokens: number, est_cost_usd: number, 
/**
 * Combined burn rate over the window (`total_tokens / window_minutes`).
 */
tokens_per_min: number, 
/**
 * Live sessions, active first then most-recent first.
 */
sessions: Array<CcLiveSession>, };
