// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subagent (sidechain) currently running under a live session — surfaced as
 * a concise line under the session's card. Keyed by the transcript `agentId`;
 * `agent`/`skill` come from its `attributionAgent`/`attributionSkill`.
 */
export type CcLiveSubagent = { agent_id: string, 
/**
 * Agent type, e.g. "general-purpose" / "Explore" (from `attributionAgent`).
 */
agent: string | null, 
/**
 * Skill driving it, when attributed (from `attributionSkill`).
 */
skill: string | null, models: Array<string>, 
/**
 * This subagent's newest in-window event timestamp (ISO-8601 UTC).
 */
last_activity: string, 
/**
 * Seconds since this subagent's last event (`now - last_event`).
 */
idle_seconds: number, 
/**
 * Assistant turns this subagent produced inside the window.
 */
messages: number, total_tokens: number, };
