// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * One currently-running Claude Code session — a session whose newest transcript
 * event lands inside the live window. The `spark` is a per-minute token series
 * (oldest→newest, one entry per bucket of [`CcLive::bucket_seconds`]) so the UI
 * can draw a heartbeat of recent activity.
 */
export type CcLiveSession = { session_id: string, 
/**
 * Short name (last path component of `cwd`).
 */
project: string | null, cwd: string | null, git_branch: string | null, models: Array<string>, 
/**
 * First/last in-window event timestamps (ISO-8601 UTC).
 */
started: string, last_activity: string, 
/**
 * Seconds since the last event (`now - last_event`); small ⇒ actively working.
 */
idle_seconds: number, 
/**
 * `active` (idle within [`CcLive::active_seconds`]) or `idle`.
 */
status: string, 
/**
 * Assistant turns inside the window.
 */
messages: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, 
/**
 * True if any in-window event came from a subagent (`isSidechain`).
 */
used_subagent: boolean, 
/**
 * Per-minute total-token buckets over the window, oldest→newest.
 */
spark: Array<number>, };
