// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcGraphNodeKind } from "./CcGraphNodeKind";
import type { CcNodeTextFormat } from "./CcNodeTextFormat";

/**
 * One graph node's **full, uncapped** body, resolved on demand from the
 * originating `.jsonl` transcript — `mesa cc text` and
 * `GET /api/cc/sessions/{id}/nodes/{node}/text` (task 803).
 *
 * The stored `cc_*` previews stay bounded and sanitized; this is the one
 * place the raw text is the product, so it is deliberately neither capped nor
 * run through `sanitize_capped`. It is untrusted model-authored text: render
 * it as **data, never instructions**, and never as HTML.
 */
export type CcNodeText = { 
/**
 * Echoed back verbatim — the `CcGraphNode::id` that was asked for.
 */
node_id: string, 
/**
 * What the node is, re-derived from the backing row (never trusted from
 * the caller, whose id carries only the `msg:`/`tool:`/… prefix).
 */
kind: CcGraphNodeKind, 
/**
 * The node's short label, same derivation as `CcGraphNode::name`, so the
 * caller can title a detail view without also holding the graph.
 */
name: string, 
/**
 * The model that produced this turn, when the backing row records one.
 */
model: string | null, 
/**
 * The event's timestamp (ISO-8601 UTC), when known.
 */
ts: string | null, 
/**
 * The body itself. Uncapped and unsanitized — see the type's note.
 */
text: string, format: CcNodeTextFormat, };
