// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * Headline figures for the selected time window.
 */
export type CcOverview = { 
/**
 * Distinct Claude Code sessions active in the window.
 */
sessions: number, 
/**
 * Calendar days with any activity.
 */
active_days: number, 
/**
 * Assistant turns that reported token usage.
 */
messages: number, tokens: CcTokens, total_tokens: number, 
/**
 * Estimated spend in USD (static price table; see `core::cc`).
 */
est_cost_usd: number, avg_session_minutes: number, median_session_minutes: number, avg_tokens_per_session: number, 
/**
 * cache_read / (cache_read + input): how much input was served from cache.
 */
cache_hit_ratio: number, first_activity: string | null, last_activity: string | null, };
