// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage rolled up by working directory (`cwd`).
 */
export type CcProjectStat = { 
/**
 * Short name (last path component of `cwd`).
 */
project: string, 
/**
 * Full working-directory path (disambiguates same-named folders).
 */
path: string, sessions: number, messages: number, total_tokens: number, est_cost_usd: number, };
