// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session stuck repeating one trivial shell command — the *shape* of a
 * wedged agent rather than its cost, and the only guard signal that can fire
 * before any money is spent (mesa task 1054).
 *
 * `command` is the full `Bash` input run through `cc::sanitize_capped`, so it
 * is bounded and control-character-free like every other transcript-derived
 * string mesa surfaces: it is untrusted model-authored text, and it is data.
 */
export type CcRepeat = { 
/**
 * The command being repeated, sanitized and capped at
 * `cc::TARGET_MAX_CHARS`.
 */
command: string, 
/**
 * How many times in a row it has just been run.
 */
count: number, };
