// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One session's tool calls rolled up by tool **name** only — never by
 * `target`, so a Bash tool is one row rather than one row per command.
 */
export type CcSessionToolStat = { 
/**
 * Untrusted transcript text — render as data.
 */
name: string, calls: number, 
/**
 * Of `calls`, those made by a subagent (non-null `agent_id`).
 */
subagent_calls: number, };
