// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One session's `Skill` invocations, keyed by the skill itself (the call's
 * `target`) — the same promotion the call tree does.
 */
export type CcSessionSkillStat = { 
/**
 * Untrusted transcript text — render as data.
 */
name: string, calls: number, };
