// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * One thread of a session: the main thread (`agent_id: None`) or one subagent.
 */
export type CcSessionThreadStat = { 
/**
 * `None` = the main thread.
 */
agent_id: string | null, 
/**
 * Agent type / skill / spawn description, from `cc_agent_runs`. All `None`
 * for a thread seen only in messages or tool calls (no run row).
 *
 * Untrusted transcript text — render as data.
 */
agent: string | null, skill: string | null, description: string | null, spawn_depth: number | null, 
/**
 * The thread's most-used model.
 */
model: string | null, messages: number, tool_calls: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, 
/**
 * First/last event in this thread (ISO-8601 UTC), when known.
 */
start: string | null, end: string | null, };
