// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcGraphEdge } from "./CcGraphEdge";
import type { CcGraphNode } from "./CcGraphNode";
import type { CcTokens } from "./CcTokens";

/**
 * One session's call tree — `GET /api/cc/sessions/{id}/graph` and
 * `mesa cc graph <SESSION_ID>`. Always a tree: every node but the root has
 * exactly one parent, so a client can lay it out without cycle-breaking.
 */
export type CcSessionGraph = { session_id: string, cwd: string | null, project: string | null, git_branch: string | null, 
/**
 * Session span (ISO-8601 UTC), when known.
 */
start: string | null, end: string | null, 
/**
 * Whole-session rolled-up usage — the honest total, since tool-node
 * tokens are not additive.
 */
tokens: CcTokens, total_tokens: number, est_cost_usd: number, 
/**
 * Root first, then the rest oldest-first.
 */
nodes: Array<CcGraphNode>, edges: Array<CcGraphEdge>, 
/**
 * True when `limit` dropped tool nodes. Subagent nodes and the tool calls
 * that spawned them are never dropped, so the tree stays connected.
 */
truncated: boolean, 
/**
 * How many tool nodes were dropped.
 */
omitted_tool_calls: number, };
