// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * One session's usage rolled up by model id.
 */
export type CcSessionModelStat = { model: string, messages: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, };
