// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcTokens } from "./CcTokens";

/**
 * One session row for the sessions table.
 */
export type CcSessionRow = { session_id: string, 
/**
 * First/last event timestamps (ISO-8601 UTC, as recorded by Claude Code).
 */
start: string, end: string, duration_minutes: number, models: Array<string>, messages: number, tokens: CcTokens, total_tokens: number, est_cost_usd: number, 
/**
 * Tool calls made in the window (main thread + subagents).
 */
tool_calls: number, 
/**
 * Subagent runs recorded under this session (not window-filtered — runs
 * have no timestamp of their own).
 */
agent_runs: number, cwd: string | null, project: string | null, git_branch: string | null, entrypoint: string | null, 
/**
 * True if any of the session's events came from a subagent (`isSidechain`).
 * Subagent transcripts reuse the parent's `sessionId`, so this is "the
 * session used a subagent", not "the session *is* a sidechain".
 */
used_subagent: boolean, };
