// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket of the activity series. Messages are the atoms and their usage is
 * additive, so these token counts are honest sums (unlike a graph node's).
 */
export type CcSessionBucket = { 
/**
 * The bucket's left edge (ISO-8601 UTC).
 */
start: string, messages: number, tool_calls: number, total_tokens: number, output_tokens: number, };
