// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcChatAsk } from "./CcChatAsk";
import type { CcChatTurn } from "./CcChatTurn";

/**
 * One session's conversation, read live off its `.jsonl` transcript —
 * `mesa cc chat` and `GET /api/cc/sessions/{id}/chat` (task 814).
 *
 * Backs the Agent sidebar's **chat view**, the rendered alternative to a
 * pane's raw terminal. Like [`CcLive`] it answers from the file rather than
 * the `cc_*` tables: the point is a session that is being written *right
 * now*, whose newest turns no ingest has seen yet — and which, for an agent
 * mesa itself just spawned, may not be in the db at all.
 *
 * Main thread only, matching `cc_prompts`: a subagent's turns live in their
 * own transcript and are not part of the conversation a human is reading.
 */
export type CcSessionChat = { 
/**
 * Echoed back verbatim — the session id that was asked for.
 */
session_id: string, 
/**
 * Oldest first. The tail of the conversation: see `truncated`.
 */
turns: Array<CcChatTurn>, 
/**
 * True when older turns were dropped — either by the caller's `limit` or
 * by the byte window this read parses (a transcript reaches tens of
 * megabytes and this is a poll). A single honest boolean rather than a
 * count: the byte window drops an *unknown* number of turns, so any
 * number here would be invented.
 */
truncated: boolean, 
/**
 * The `AskUserQuestion` call this session is **waiting on**, when it is
 * waiting on one (task 866) — the one turn a reader can do something
 * about rather than only watch. Derived on every read from the same
 * window the turns come from (the last such `tool_use` carrying no
 * `tool_result`), never stored, and `None` for every session that is not
 * blocked on a question.
 */
pending_question: CcChatAsk | null, };
