// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A four-way token split shared by every CC aggregate. `cache_read` is context
 * served from the prompt cache (cheap); `cache_creation` is context written to
 * it (a premium over plain input).
 */
export type CcTokens = { input: number, output: number, cache_read: number, cache_creation: number, };
