// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool usage rolled up by `(name, caller)` over `tool_use` blocks.
 */
export type CcToolStat = { name: string, 
/**
 * The `tool_use.caller`, verbatim (e.g. `{"type":"direct"}`); null when
 * the block carried none.
 */
caller: string | null, calls: number, 
/**
 * Distinct sessions that made at least one such call.
 */
sessions: number, };
