// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rate-limit window: how much of the plan limit is used and when it resets.
 */
export type CcUsageWindow = { 
/**
 * Percent of the plan limit consumed (0–100).
 */
utilization: number, 
/**
 * When the window resets (ISO-8601 UTC), if known.
 */
resets_at: string | null, };
