// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcUsageExtra } from "./CcUsageExtra";
import type { CcUsageWindow } from "./CcUsageWindow";

/**
 * Live Claude Code subscription usage — the `/usage` data fetched from
 * Anthropic's OAuth usage endpoint (`mesa cc usage` / `GET /api/cc/usage`).
 * Unlike the rest of the CC dashboard, which parses local transcripts, this is
 * a live network read (see `core::usage`). `utilization` is 0–100 percent of
 * the plan limit; `resets_at` is ISO-8601 UTC.
 */
export type CcUsage = { 
/**
 * Rolling 5-hour session window.
 */
five_hour: CcUsageWindow | null, 
/**
 * Rolling 7-day window (all models).
 */
seven_day: CcUsageWindow | null, 
/**
 * Rolling 7-day window scoped to Opus, when the plan meters it separately.
 */
seven_day_opus: CcUsageWindow | null, 
/**
 * Rolling 7-day window scoped to Sonnet, when metered separately.
 */
seven_day_sonnet: CcUsageWindow | null, 
/**
 * Pay-as-you-go extra-usage credits, when enabled on the plan.
 */
extra_usage: CcUsageExtra | null, 
/**
 * Human plan label (e.g. "Max 20x"), from `~/.claude.json`, when known.
 */
plan_tier: string | null, 
/**
 * Unix seconds at which this snapshot was fetched.
 */
fetched_at_unix: number, };
