// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pay-as-you-go extra-usage credit balance.
 */
export type CcUsageExtra = { is_enabled: boolean, 
/**
 * Monthly credit cap in `currency`, if set.
 */
monthly_limit: number | null, used_credits: number, currency: string, };
