// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rebindable action: what the config says, and what mesa ships behind it.
 */
export type ConfigKeymapAction = { 
/**
 * The action id (`command-palette`, `focus-left`, …). The label beside it
 * is the page's own: it is copy, not contract.
 */
action: string, 
/**
 * The configured chords, or `null` when the config says nothing about
 * this action — then `default` is what applies. A **list**, because the
 * spatial nav answers to a letter and an arrow alike.
 */
value: Array<string> | null, 
/**
 * The chords mesa ships for this action, so the editor can show what
 * "reset" means without a second copy of the table.
 */
default: Array<string>, };
