// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRates } from "./ModelRates";

/**
 * One model-family price row as the Settings page sees it (`core::config`,
 * `docs/config.md`). Like [`ConfigCommand`] this is a view of
 * `~/.mesa/config.json`, not db state, and the same null-means-fallback rule
 * applies.
 */
export type ConfigPrice = { 
/**
 * The model-family **prefix**, matched with `starts_with` against a
 * transcript's model id (`claude-opus`, `claude-opus-5-mini`, …).
 */
prefix: string, 
/**
 * The configured rates, or `null` when the prefix is absent from the
 * config — then `default` is what applies.
 */
value: ModelRates | null, 
/**
 * The built-in rates behind this prefix, or `null` for a prefix the user
 * added that the binary knows nothing about (then `value` is the only
 * thing keeping the row alive, and clearing it deletes the row).
 */
default: ModelRates | null, };
