// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The live-conversation settings as the Settings page sees them
 * (`core::config`, `docs/config.md`, mesa task 867) — a fifth view of
 * `~/.mesa/config.json`, with the same null-means-fallback rule as
 * [`ConfigWatchers`].
 */
export type ConfigLive = { 
/**
 * The instruction block a live agent is spawned with, or `null` when the
 * config says nothing — then `default_prompt` is what the agent gets.
 */
prompt: string | null, 
/**
 * The prompt mesa ships (`core::live::AGENT_PROMPT`), so the editor can
 * show what blank means — and offer it as the starting point for an edit
 * — without a copy of it in TypeScript.
 */
default_prompt: string, 
/**
 * How long a settled dictation draft waits before the page sends it, in
 * milliseconds, or `null` when the config says nothing — then
 * `auto_send_ms_default` is the wait (mesa task 886).
 */
auto_send_ms: number | null, 
/**
 * The wait mesa ships (`core::config::DEFAULT_LIVE_AUTO_SEND_MS`), so the
 * page has the number to fall back to without a second copy of it in
 * TypeScript.
 */
auto_send_ms_default: number, };
