// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The watcher settings as the Settings page sees them (`core::config`,
 * `docs/config.md`, mesa task 777). A third view of `~/.mesa/config.json`
 * beside [`ConfigCommand`] and [`ConfigPrice`], with the same
 * null-means-fallback rule: an absent value is the built-in default, and
 * writing `null` back is how the user restores it.
 */
export type ConfigWatchers = { 
/**
 * How many watcher agents the todo-watcher may have running per project,
 * or `null` when the config says nothing — then `todo_concurrency_default`
 * is what applies.
 */
todo_concurrency: number | null, 
/**
 * The built-in limit mesa ships (1), so the editor can show what blank
 * means without hardcoding it.
 */
todo_concurrency_default: number, };
