// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `naru-audio` settings as the Settings page sees them (`core::config`,
 * `docs/config.md`, mesa task 1388): which engine the **server** runs speech
 * through and where the daemon listens, each verbatim (`null` when the
 * config says nothing) beside its built-in.
 */
export type ConfigAudio = { 
/**
 * The configured daemon URL, or `null`. `NARU_AUDIO_URL` overrides it
 * where it is used, not here.
 */
url: string | null, 
/**
 * The built-in daemon URL (`http://127.0.0.1:7870`).
 */
url_default: string, 
/**
 * `"legacy"`, `"naru-audio"`, or `null`.
 */
engine: string | null, 
/**
 * The built-in engine (`"legacy"`).
 */
engine_default: string, };
