// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The live-conversation settings as the Settings page sees them
 * (`core::config`, `docs/config.md`, mesa task 867) — a fifth view of
 * `~/.mesa/config.json`, with the same null-means-fallback rule as
 * [`ConfigWatchers`].
 *
 * This used to carry the instruction block a live agent is spawned with too
 * (`prompt`/`default_prompt`), but that moved to the library as of mesa task
 * 919 — it is now the `mesa-live` agent definition (mesa task 1068), edited
 * on `#/library` rather than here.
 */
export type ConfigLive = { 
/**
 * How long a settled dictation draft waits before the page sends it, in
 * milliseconds, or `null` when the config says nothing — then
 * `auto_send_ms_default` is the wait (mesa task 886).
 */
auto_send_ms: number | null, 
/**
 * The wait mesa ships (`core::config::DEFAULT_LIVE_AUTO_SEND_MS`), so the
 * page has the number to fall back to without a second copy of it in
 * TypeScript.
 */
auto_send_ms_default: number, };
