// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configurable agent-spawn command as the Settings page sees it
 * (`core::config`, `docs/config.md`). Not stored in the db — this is a view
 * of `~/.mesa/config.json`, which is read fresh on every spawn.
 */
export type ConfigCommand = { 
/**
 * The config key: `todo-watcher`, `refine-watcher`, `inbox-watcher`
 * or `agent-spawn`.
 */
action: string, 
/**
 * The configured template, or `null` when the key is absent or blank.
 * Null is "falling back to `default`", never "run nothing".
 */
value: string | null, 
/**
 * The built-in template used while `value` is null.
 */
default: string, 
/**
 * The `{}`-delimited placeholders this action offers. Any other one is a
 * save-time error, so the editor can list these as the whole vocabulary.
 * Substituted in single-line (argv) mode only.
 */
placeholders: Array<string>, 
/**
 * The environment variables this action sets when the value is a
 * **multi-line script** (`bash -c`), positionally matching
 * `placeholders` — a script reads `$MESA_NAME`, never `{name}`. A
 * variable with no value on a given call is left unset.
 */
env_vars: Array<string>, };
