// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The listen settings as the Settings page sees them (`core::config`,
 * `docs/config.md`, mesa task 955) — the input-side mirror of
 * [`ConfigSpeech`]: the model the external `auris` speech-to-text binary is
 * run with, plus the models the installed binary offers.
 */
export type ConfigListen = { 
/**
 * The configured model `live transcribe` runs `auris` with, or `null`
 * when the config says nothing — then no `-m` is passed at all and
 * `auris` picks its own default.
 */
model: string | null, 
/**
 * Every model the installed `auris` reports (`--list-models`), so the
 * editor can offer a list. **Empty means mesa could not ask** — a missing
 * or uncooperative binary — never "there are no models", so an empty
 * list is a reason to accept a typed name, not to refuse one.
 */
models: Array<string>, };
