// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigKeymapAction } from "./ConfigKeymapAction";

/**
 * The global keyboard shortcuts as the Settings page sees them
 * (`core::config`, `docs/keyboard.md`, mesa task 1079) — an eighth view of
 * `~/.mesa/config.json`, with the same null-means-fallback rule as
 * [`ConfigWatchers`]: an action the config says nothing about answers to the
 * chords mesa ships, and writing `null` back is how the user restores them.
 */
export type ConfigKeymap = { 
/**
 * Every action mesa binds, in the order `config::KEYMAP_ACTIONS` ships
 * them — a list rather than a map so the page renders the rows in one
 * settled order without holding a second copy of it.
 */
actions: Array<ConfigKeymapAction>, };
