// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The cost-guard settings as the Settings page sees them (`core::config`,
 * `docs/cost-guard.md`, mesa task 1018) — a sixth view of
 * `~/.mesa/config.json`, with the same null-means-fallback rule as
 * [`ConfigWatchers`]: an absent value is the built-in threshold, and writing
 * `null` back is how the user restores it.
 */
export type ConfigGuard = { 
/**
 * Dollars of estimated spend in the guard window at which a live session
 * is reported, or `null` when the config says nothing.
 */
cost_usd: number | null, 
/**
 * The built-in dollar ceiling mesa ships.
 */
cost_usd_default: number, 
/**
 * Tokens in the guard window at which a live session is reported, or
 * `null` when the config says nothing.
 */
total_tokens: number | null, 
/**
 * The built-in token ceiling mesa ships.
 */
total_tokens_default: number, 
/**
 * The share of a session's tokens that must be cache reads for the
 * spin-loop rule to fire (0.5..=1.0), or `null` for the built-in.
 */
cache_read_share: number | null, 
/**
 * The built-in cache-read share mesa ships.
 */
cache_read_share_default: number, 
/**
 * The token floor under which the spin-loop rule never fires — what stops
 * a tiny session at 100% cache-read from being called a runaway — or
 * `null` for the built-in.
 */
cache_read_min_tokens: number | null, 
/**
 * The built-in spin-loop token floor mesa ships.
 */
cache_read_min_tokens_default: number, };
