// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The speech settings as the Settings page sees them (`core::config`,
 * `docs/config.md`, mesa task 822) — a fourth view of `~/.mesa/config.json`,
 * with the same null-means-fallback rule as [`ConfigWatchers`].
 */
export type ConfigSpeech = { 
/**
 * The configured voice for the inbox's play button, or `null` when the
 * config says nothing — then the synthesiser's own default applies and
 * mesa passes no `-v` at all.
 */
voice: string | null, 
/**
 * Every voice the installed `kokoro-rs` reports (`--list-voices`), so the
 * editor can offer a list. **Empty means mesa could not ask** — a missing
 * or uncooperative binary — never "there are no voices", so an empty list
 * is a reason to accept a typed name, not to refuse one.
 */
voices: Array<string>, };
