// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A storyboard's diagram style, chosen at creation and immutable thereafter
 * (no field on `StoryboardPatch` — the same structural-immutability posture
 * as `project_id`/`author`). Picks the shape set offered for its frames: a
 * `storyboard` board takes the generic frame card, a `flowchart` board takes
 * `process`/`decision`/`start_end` node shapes, an `erd` board takes only the
 * `entity` shape, and a `brainstorm` board takes `central`/`idea` mind-map
 * shapes.
 */
export type DiagramType = "storyboard" | "flowchart" | "erd" | "brainstorm";
