// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A diagram's style, chosen at creation and immutable thereafter
 * (no field on `DiagramPatch` — the same structural-immutability posture
 * as `project_id`/`author`). Picks the shape set offered for its frames and
 * the connector markers its edges may carry — see [`DiagramType::shapes`],
 * [`DiagramType::allows_generic_frame`] and [`DiagramType::edge_markers`],
 * which are the single source of truth both `Store`'s validators and
 * `mesa diagram types` read.
 */
export type DiagramType = "storyboard" | "flowchart" | "erd" | "brainstorm";
