// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagram } from "./Diagram";
import type { Frame } from "./Frame";
import type { FrameEdge } from "./FrameEdge";

/**
 * The full contents of one diagram: the board plus all of its frames and
 * edges. Returned by `show` and echoed by `delete`, so a client renders (or
 * recovers) an entire canvas from a single object.
 */
export type DiagramView = { diagram: Diagram, frames: Array<Frame>, edges: Array<FrameEdge>, };
