// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summed line/file counts over a set of commits (`core::git::diff_stat`,
 * task 920). A bare triple rather than folding into `TaskReceipt` inline so
 * it stays independently testable against `git.rs`'s `parse_numstat`, the
 * same split `GitCommit`/`GitCommitFile` already keep from their owning
 * records.
 */
export type DiffStat = { 
/**
 * Distinct paths touched across every summed commit, not a per-commit
 * sum (see `core::git::diff_stat`).
 */
files_changed: number, insertions: number, deletions: number, };
