// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subdirectory entry in a [`DirListing`] (see `core::files::list_dir`).
 * Directories only — this endpoint never lists files (see arch.md #4).
 */
export type DirEntry = { 
/**
 * Basename.
 */
name: string, 
/**
 * Absolute path (parent's canonical path + this basename). For a
 * symlinked directory this is the symlink's own location, not its
 * resolved target — `metadata()` follows the link to confirm it's a
 * directory, but `path` is never further-resolved, so `basename(path)
 * == name` always holds.
 */
path: string, };
