// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

/**
 * `GET /api/fs/dirs` response — a single-level, non-recursive listing of one
 * directory's subdirectories, for the web UI's new-project folder picker.
 * Unlike [`FileTreeEntry`]/[`ProjectFileTree`], this is not rooted at any
 * project's `local_path`: `path` is whatever absolute filesystem path the
 * caller asked for (see `.scratch/arch.md` #0, mesa task 405).
 */
export type DirListing = { 
/**
 * Canonical absolute path of the directory actually listed.
 */
path: string, 
/**
 * Canonical absolute path of `path`'s parent, or None at `/`. Lets the
 * frontend implement "up one level" without doing its own path math.
 */
parent: string | null, entries: Array<DirEntry>, };
