// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a `FrameEdge`'s line is drawn (mesa task 854). `None` on
 * `FrameEdge.style` is today's rendering — a solid line — so an edge that
 * predates the feature is byte-identical; `solid` is the same picture said
 * explicitly.
 */
export type EdgeStyle = "solid" | "dashed" | "dotted";
