// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one end of a `FrameEdge` is decorated with (mesa task 854). Two
 * families, told apart by which board types accept them
 * ([`DiagramType::edge_markers`]): the **general** family draws on any board,
 * while the **cardinality** family states an ERD relation's multiplicity and
 * is therefore accepted only on an `erd` board.
 *
 * `EdgeMarker::None` and `Option::None` are different answers: `None` on
 * `FrameEdge.from_marker`/`to_marker` is the default — today's rendering, no
 * start marker and a closed arrowhead at the `to` end — while
 * `EdgeMarker::None` explicitly draws nothing at that end.
 */
export type EdgeMarker = "none" | "arrow" | "hollow_arrow" | "circle" | "diamond" | "crows_foot" | "one" | "zero_or_one" | "one_or_many" | "zero_or_many";
