// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{id}/files/content` response (see `core::files::read_file`).
 */
export type FileContentView = { path: string, is_binary: boolean, 
/**
 * "" when is_binary is true — binary bytes are never put on the wire.
 */
content: string, truncated: boolean, 
/**
 * Extension-derived language tag (e.g. "rs" -> "rust"), or None when
 * unrecognized. "" is never used in place of None here.
 */
language: string | null, };
