// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node in a project's file tree, rooted at local_path (see
 * `core::files::tree_of`). `children` is `Some(_)` for every directory
 * (possibly `[]` — empty, excluded, or depth-capped) and `None` for every
 * file — the discriminant IS `is_dir`, `children` is never used to infer it.
 */
export type FileTreeEntry = { 
/**
 * Basename.
 */
name: string, 
/**
 * Relative to local_path, "/"-separated.
 */
path: string, is_dir: boolean, children: Array<FileTreeEntry> | null, };
