// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hit in a project-wide file search (mesa task 813, see
 * `core::files::search_files`) — one *match*, not one line: a line holding
 * two hits produces two of these, the way every editor's search panel lists
 * them.
 *
 * The match's own offsets are deliberately NOT on the wire. `text` is a
 * snippet shaped server-side (leading indentation dropped, windowed around
 * the match, `…` marking either cut), and the panel re-runs the same literal
 * scan over it to paint the highlight — the client already owns that scan
 * (`fileFind.ts`, the in-file find bar), and a char offset computed in Rust
 * is not a UTF-16 offset in JS. The worst a disagreement can do is leave a
 * row unhighlighted, never mislocate the result.
 */
export type FileSearchMatch = { 
/**
 * 1-based line number, counted over the same capped bytes
 * [`FileContentView`] carries — so opening the file and revealing this
 * line can never point past what the viewer will show.
 */
line: number, 
/**
 * The snippet to paint. Never the raw line: see the type doc.
 */
text: string, };
