// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a single directory level of a project's file tree, rooted at
 * local_path (see `core::files::tree_level`). Lazy tree walk (mesa task
 * 410): a response only ever carries ONE level — no `children` field,
 * unlike the whole-tree walk this replaced. A directory's own contents are
 * fetched by a separate call passing this entry's `path` as `?path=`; the
 * frontend tracks "not yet fetched" itself, off the wire.
 */
export type FileTreeEntry = { 
/**
 * Basename.
 */
name: string, 
/**
 * Relative to local_path, "/"-separated.
 */
path: string, is_dir: boolean, };
