// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchMatch } from "./FileSearchMatch";

/**
 * One file's hits in a project-wide file search (mesa task 813).
 */
export type FileSearchFile = { 
/**
 * Relative to local_path, "/"-separated — the same path shape
 * [`FileTreeEntry`] uses, so a result opens through the existing content
 * route unchanged.
 */
path: string, 
/**
 * Extension-derived language tag, same table as [`FileContentView`] —
 * the panel tints a result group with it exactly as the tree tints a row.
 */
language: string | null, matches: Array<FileSearchMatch>, 
/**
 * True iff this file holds more matches than were returned.
 */
truncated: boolean, };
