// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameShape } from "./FrameShape";

/**
 * One card on a storyboard, positioned freely on the canvas. `x`/`y` are the
 * top-left corner and `w`/`h` the size, in abstract canvas units the web
 * renders as pixels. `body` is free text (markdown by convention). `task_id`
 * optionally links the frame to an existing task in the *same project* — a
 * soft reference that is set to null if the task is later deleted.
 */
export type Frame = { id: number, storyboard_id: number, title: string, body: string | null, x: number, y: number, w: number, h: number, 
/**
 * Free-text colour hint for the web canvas (a CSS colour, e.g. `#00e5ff`).
 */
color: string | null, task_id: number | null, 
/**
 * Free-text actor id that created the frame (an agent name or "user").
 */
author: string | null, 
/**
 * The frame's node shape, fixed at creation, validated against the
 * board's `diagram_type` (see `FrameShape`). `None` is the generic card.
 */
shape: FrameShape | null, created_at: string, updated_at: string, };
