// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSide } from "./AnchorSide";
import type { EdgeMarker } from "./EdgeMarker";
import type { EdgeStyle } from "./EdgeStyle";
import type { Waypoint } from "./Waypoint";

/**
 * A directed connection from one frame to another on the same diagram.
 * Unlike task dependencies, diagram edges may form cycles freely — a
 * diagram is a freeform diagram, not a dependency graph. Self-edges
 * (`from_frame == to_frame`) are the only rejected shape.
 */
export type FrameEdge = { id: number, diagram_id: number, from_frame: number, to_frame: number, label: string | null, 
/**
 * Free-text actor id that created the edge (an agent name or "user").
 */
author: string | null, created_at: string, 
/**
 * Ordered routing anchors from `from_frame`'s end to `to_frame`'s end.
 * Always a plain array — `[]` means "no waypoints", never `null`.
 */
waypoints: Array<Waypoint>, 
/**
 * Side of `from_frame` this edge is locked to, if any. `None` means
 * floating — routing picks the nearest side live, exactly today's
 * behavior.
 */
from_anchor: AnchorSide | null, 
/**
 * Side of `to_frame` this edge is locked to, if any. Same contract as
 * `from_anchor`, independent per endpoint.
 */
to_anchor: AnchorSide | null, 
/**
 * How the connector's line is drawn. `None` renders exactly as today
 * (solid) — see `EdgeStyle`. Unlike `shape`/`diagram_type` this is
 * mutable: restyling a connector never moves it into another type
 * system, so there is nothing for immutability to protect.
 */
style: EdgeStyle | null, 
/**
 * Decoration at the `from_frame` end. `None` renders exactly as today
 * (nothing at the start) — see `EdgeMarker`. Validated against the
 * board's `diagram_type`: the cardinality family is `erd`-only.
 */
from_marker: EdgeMarker | null, 
/**
 * Decoration at the `to_frame` end. `None` renders exactly as today (a
 * closed arrowhead). Same contract as `from_marker`, independent per
 * endpoint.
 */
to_marker: EdgeMarker | null, };
