// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorSide } from "./AnchorSide";
import type { Waypoint } from "./Waypoint";

/**
 * A directed connection from one frame to another on the same storyboard.
 * Unlike task dependencies, storyboard edges may form cycles freely — a
 * storyboard is a freeform diagram, not a dependency graph. Self-edges
 * (`from_frame == to_frame`) are the only rejected shape.
 */
export type FrameEdge = { id: number, storyboard_id: number, from_frame: number, to_frame: number, label: string | null, 
/**
 * Free-text actor id that created the edge (an agent name or "user").
 */
author: string | null, created_at: string, 
/**
 * Ordered routing anchors from `from_frame`'s end to `to_frame`'s end.
 * Always a plain array — `[]` means "no waypoints", never `null`.
 */
waypoints: Array<Waypoint>, 
/**
 * Side of `from_frame` this edge is locked to, if any. `None` means
 * floating — routing picks the nearest side live, exactly today's
 * behavior.
 */
from_anchor: AnchorSide | null, 
/**
 * Side of `to_frame` this edge is locked to, if any. Same contract as
 * `from_anchor`, independent per endpoint.
 */
to_anchor: AnchorSide | null, };
