// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A frame's node shape, chosen at creation and immutable thereafter (no
 * field on `FramePatch` — mirrors `DiagramType`'s posture, for the same
 * reason: a board should never hold a shape from the "wrong" type system).
 * `None` on `Frame.shape` means the generic card, valid only on a
 * `storyboard`-type board; `Store::create_frame` validates a given shape
 * against the parent board's `DiagramType`.
 */
export type FrameShape = "process" | "decision" | "start_end" | "entity" | "central" | "idea";
