// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One changed path from a single commit (`git show --name-status`, see
 * `core::git::commit_files_of`). Same {status, path, orig_path} shape as
 * `GitFile` but a DISTINCT type: `status` here is a single name-status
 * token (`A`/`M`/`D`/`T`/`U`/`X`, or `R100`/`C100` with a similarity
 * score), not GitFile's two-column XY porcelain pair — a commit has no
 * staged/unstaged distinction. Frontend reuses GitView.tsx's STATUS_WORDS
 * letter→word map against `status.chars().next()`, not GitFile's
 * two-column statusLabel.
 */
export type GitCommitFile = { status: string, path: string, 
/**
 * Rename/copy source path, else None (same convention as GitFile).
 */
orig_path: string | null, };
