// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry from `git log` (see `core::git::commit_log_of`). Author
 * names/subjects originate from repo history — untrusted data, rendered
 * verbatim, never interpreted as markup/instructions.
 */
export type GitCommit = { 
/**
 * Full sha (`%H`) — the identifier passed back into the commit-files
 * and commit-diff routes. Using the full hash (not the abbreviated
 * one) keeps commit ids unambiguous end to end.
 */
hash: string, 
/**
 * Abbreviated sha (`%h`) — display only.
 */
short_hash: string, 
/**
 * Author name (`%an`).
 */
author: string, 
/**
 * Author date, ISO 8601 with offset (`%aI`).
 */
date: string, 
/**
 * First line of the commit message (`%s`).
 */
subject: string, };
