// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{id}/git/diff` response. Also reused verbatim for
 * `GET /api/projects/{id}/git/commits/{sha}/diff` (see
 * `core::git::commit_file_diff_of`) — the fields mean exactly the same
 * thing whether the diff is against the working tree or `git show <sha>`.
 */
export type GitFileDiff = { path: string, 
/**
 * Unified diff, plain text, possibly "" (no content change, or the
 * underlying git call failed — quiet, never an error). Binary files
 * carry git's own "Binary files ... differ" line.
 */
diff: string, };
