// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One changed/untracked/conflicted path from `git status --porcelain=v2`
 * (see `core::git::view_of`).
 */
export type GitFile = { 
/**
 * Two-char XY status pair, verbatim from porcelain v2:
 * '1' lines → XY (e.g. "M.", ".M", "MM"), '2' lines → XY (e.g. "R."),
 * '?' lines → "??", 'u' lines → XY (e.g. "UU").
 * X = staged column, Y = unstaged column, '.' = unchanged.
 */
status: string, 
/**
 * Current path (rename target for '2' lines).
 */
path: string, 
/**
 * Rename/copy source path ('2' lines only), else None.
 */
orig_path: string | null, };
