// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFile } from "./GitFile";
import type { GitStatus } from "./GitStatus";

/**
 * The live repo behind a project's `local_path`: the sidebar summary plus
 * the per-file change list (see `core::git::view_of`).
 */
export type GitRepoView = { 
/**
 * Reuses the existing GitStatus (branch, dirty, ahead, behind).
 */
status: GitStatus, 
/**
 * Same order git printed them (stable enough; UI does not re-sort).
 */
files: Array<GitFile>, };
