// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Working-tree git status of one repo folder (see `core::git`). Decorative
 * sidebar data: absence (no repo, no git) is represented by omission, not by
 * a degenerate value.
 */
export type GitStatus = { 
/**
 * Current branch name; short commit id when HEAD is detached.
 */
branch: string, 
/**
 * Changed + untracked + conflicted paths (working tree and index).
 */
dirty: number, 
/**
 * Commits ahead of upstream; 0 when no upstream is set.
 */
ahead: number, 
/**
 * Commits behind upstream; 0 when no upstream is set.
 */
behind: number, };
