// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry from `git worktree list --porcelain` (see
 * `core::git::worktrees_of`).
 */
export type GitWorktree = { 
/**
 * Absolute path of this worktree's checkout.
 */
path: string, 
/**
 * Checked-out branch name; None when detached.
 */
branch: string | null, 
/**
 * HEAD commit, full sha.
 */
head: string, 
/**
 * True for the worktree at the project's own `local_path` — the one
 * mesa is anchored to, highlighted in the UI as "current".
 */
is_current: boolean, };
