// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The host's display adapter, as `system_profiler` reports it (macOS only —
 * `SystemInfo::gpu` is `None` everywhere else). `usage_pct` is always `None`
 * today: real utilisation needs privileged `powermetrics`, so mesa reports
 * nothing rather than a number it cannot stand behind.
 */
export type GpuInfo = { name: string, 
/**
 * Absent on Apple silicon, where the GPU shares system memory.
 */
vram_bytes: number | null, usage_pct: number | null, };
