// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The captured outcome of one hook command run (see `core::hooks`). A
 * nonzero `exit_code` is the hook's own result, not a transport failure —
 * the CLI and API report it inside this object with a success status.
 */
export type HookRun = { 
/**
 * Hook point name, e.g. "task-execute".
 */
hook: string, 
/**
 * The configured shell command that ran.
 */
command: string, 
/**
 * Process exit code; -1 when the hook was killed by a signal.
 */
exit_code: number, 
/**
 * Captured stdout, truncated to 64 KiB.
 */
stdout: string, 
/**
 * Captured stderr, truncated to 64 KiB.
 */
stderr: string, };
