// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveOutcome } from "./ArchiveOutcome";
import type { InboxKind } from "./InboxKind";

/**
 * A global inbox item: a free-text project-update request an agent sends to
 * one shared inbox, not yet tied to any project. The inbox lives *above*
 * projects: items arrive unassigned, and a person later routes each one to the
 * project it belongs to by setting `project_id`. The `body` is the message
 * (markdown by convention) and is treated strictly as data, never instructions.
 */
export type InboxItem = { id: number, 
/**
 * The project this item has been assigned to, or null while it sits
 * unassigned in the global inbox. Set when a person triages the item; an
 * agent never assigns at send time. If the assigned project is deleted the
 * item returns to unassigned (the FK is `ON DELETE SET NULL`).
 */
project_id: number | null, 
/**
 * Free-text actor id of the sender (an agent name or "user").
 */
author: string | null, 
/**
 * The message body (markdown by convention). Required.
 */
body: string, 
/**
 * What the item is for (mesa task 846): a summary a person reads, or a
 * change request the inbox-watcher triages. Set at creation and never
 * changed — it is what the sender meant, not a state the reader moves.
 */
kind: InboxKind, 
/**
 * When the item was sent (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the item was last changed — e.g. assigned (SQLite `datetime`, UTC).
 */
updated_at: string, 
/**
 * When the item was **first** read, or null while it is unread (mesa task
 * 831). Stamped once and never moved or cleared: an item is read after it
 * has been opened long enough to take in, or heard through the play
 * button, and re-reading it says nothing new.
 */
read_at: string | null, 
/**
 * When the item was archived — set aside without being triaged — or null
 * while it is live (mesa task 845). Unlike `read_at` this toggles:
 * archiving is a place an item sits, so un-archiving clears the stamp.
 */
archived_at: string | null, 
/**
 * Why the item was set aside (mesa task 1168) — the archiver's verdict
 * ("duplicate of task 12", "shipped in abc123", "completion summary; the
 * record is task 40's result"), at most 1000 chars, or null. Written only
 * by an archive and cleared by the un-archive, so it is null exactly when
 * `archived_at` is.
 */
archive_reason: string | null, 
/**
 * How the item was disposed of (mesa task 1248) — the enumerated twin of
 * `archive_reason` above, one of four fixed words rather than prose, so
 * the answers can be counted. It rides with the stamp the same way:
 * written only by an archive and cleared by the un-archive, so it is null
 * exactly when `archived_at` is.
 */
archive_outcome: ArchiveOutcome | null, 
/**
 * The task this item **became** (mesa task 1269), or null for an item that
 * was never assigned. Assigning an item converts it into a backlog task
 * and archives the item with `archive_outcome: converted-to-task`; this is
 * the pointer to that task, so the archived request and the work it turned
 * into are reachable from each other. Deliberately **not** `task_id`
 * below, which is the *origin* task the item reports on: an item is about
 * one piece of work and may become another. Null again if the created task
 * is later deleted (the FK is `ON DELETE SET NULL`, so a deleted task
 * loses the pointer rather than the archived record of the request).
 */
converted_task_id: number | null, 
/**
 * The task this item is **about** (mesa task 847) — required at creation,
 * because every item arrives from an agent working a task and an item with
 * no origin cannot say where it came from. Null only on a row that
 * predates 847, or whose task was later deleted (the FK is
 * `ON DELETE SET NULL`, like the item's own `project_id`). It is not the
 * item's *assignment*: `project_id` stays null until a person triages.
 */
task_id: number | null, 
/**
 * The origin task's `name`, **derived on every read** from that task's
 * description by the one `task_name` implementation — never stored, so it
 * cannot go stale against a task that was re-described. Null exactly when
 * `task_id` is.
 */
task_name: string | null, 
/**
 * The origin task's project name, derived on every read the same way.
 * This is the project the item is *about*; `project_id` above is where it
 * was triaged to, which is a different question and stays null.
 */
project_name: string | null, };
