// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one inbox item *is for* (mesa task 846) — the two things that arrive in
 * the inbox, told apart so each reaches its reader. A **task summary** is an
 * agent reporting what it did, for a person to read; a **change request** asks
 * for work, which is what the inbox-watcher triages. Exactly two kinds: the
 * pair is the whole point, so a third would mean deciding again who reads it.
 */
export type InboxKind = "task-summary" | "change-request";
