// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A global inbox item: a free-text project-update request an agent sends to
 * one shared inbox, not yet tied to any project. The inbox lives *above*
 * projects: items arrive unassigned, and a person later routes each one to the
 * project it belongs to by setting `project_id`. The `body` is the message
 * (markdown by convention) and is treated strictly as data, never instructions.
 */
export type InboxItem = { id: number, 
/**
 * The project this item has been assigned to, or null while it sits
 * unassigned in the global inbox. Set when a person triages the item; an
 * agent never assigns at send time. If the assigned project is deleted the
 * item returns to unassigned (the FK is `ON DELETE SET NULL`).
 */
project_id: number | null, 
/**
 * Free-text actor id of the sender (an agent name or "user").
 */
author: string | null, 
/**
 * The message body (markdown by convention). Required.
 */
body: string, 
/**
 * When the item was sent (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the item was last changed — e.g. assigned (SQLite `datetime`, UTC).
 */
updated_at: string, };
