// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of applying one resolution from `POST /api/library/sync`.
 * Apply is per-row, not all-or-nothing across the batch: a failing row is
 * reported here and the rest still apply.
 */
export type LibrarySyncResult = { path: string, 
/**
 * `mesa | disk | skip`, echoing the resolution this result answers.
 */
choice: string, applied: boolean, error: string | null, };
