// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryHookRegistration } from "./LibraryHookRegistration";
import type { LibraryScope } from "./LibraryScope";

/**
 * A hook command in `.claude/settings.json` whose script lives **outside**
 * `.claude/hooks/` (mesa task 1128) — invisible to the library, which only
 * ever sees that directory, and offered for *adoption*: moving the script
 * in and rewriting the command(s) that name it, on the user's explicit
 * action and never on a read. One row per script, however many events name
 * it.
 */
export type LibraryOrphanHook = { scope: LibraryScope, project_id: number | null, 
/**
 * The settings file the command(s) were read from.
 */
settings_path: string, 
/**
 * The script's absolute path on this machine, the token expanded
 * (`~/`, `$HOME/`, `$CLAUDE_PROJECT_DIR/`) and canonicalised — the key
 * `adopt` takes.
 */
path: string, 
/**
 * Whether that file is on disk. A registration naming a missing file is
 * still listed — it fires and errors every session, which is worth
 * seeing — but cannot be adopted.
 */
exists: boolean, 
/**
 * The library name adoption would give it: the file's own name, since a
 * hook's name is its whole filename.
 */
name: string, 
/**
 * Every command naming this script, across events and groups.
 */
registrations: Array<LibraryHookRegistration>, 
/**
 * Why adoption would be refused right now — the name unusable, the
 * destination `.claude/hooks/<name>` already taken, or a hook item of
 * that name already at this scope — or `None` when it would go through.
 */
conflict: string | null, };
