// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one bundle item compares to what this instance already holds —
 * [`core::library::import_preview`]'s verdict, and the only four shapes an
 * import can meet. Deliberately *not* [`LibrarySyncStatus`]'s seven: a
 * bundle carries no sync baseline (it is a fact about the exporting
 * machine's disk alone), so there is no third string to classify against.
 * Two bodies and a choice is the whole of it — plus the one case where
 * there are not even two bodies, because the item could not be matched at
 * all.
 */
export type LibraryImportStatus = "new" | "identical" | "conflict" | "unresolvable";
