// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a synced path's mesa body (M) compares to the file on disk (D) against
 * the last-agreed baseline (B) — `core::library::classify`'s result, and the
 * one decision table `mesa library sync status` reports.
 */
export type LibrarySyncStatus = "in-sync" | "mesa-new" | "disk-deleted" | "mesa-changed" | "disk-changed" | "both-changed" | "disk-new";
