// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place a `hook` library item is wired into `.claude/settings.json`
 * (mesa task 1115) — a hook file on disk does nothing until Claude Code is
 * told to run it, and this is that instruction.
 *
 * Named `LibraryHook*` rather than `Hook*` because mesa has an unrelated
 * hooks feature of its own (`core::hooks`, [`HookRun`], `~/.mesa/hooks.json`
 * and the `task-execute` event); these two share a word and nothing else.
 */
export type LibraryHookRegistration = { 
/**
 * A Claude Code hook event — one of `core::library::HOOK_EVENTS`.
 */
event: string, 
/**
 * The tool/source pattern the group carries; `*` when it names none.
 */
matcher: string, 
/**
 * The command string exactly as it appears in the settings file, which
 * need not be the one mesa would have written (a hand-edited
 * `bash …/stop-notify.sh --quiet` still counts as this hook).
 */
command: string, };
