// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryDiffKind } from "./LibraryDiffKind";

/**
 * One line of a sync row's diff. Line numbers are 1-based and present only
 * on the side the line exists in; a line carrying **neither** is
 * `core::library::diff_lines`'s truncation marker, the one line that is not
 * content from either side.
 */
export type LibraryDiffLine = { kind: LibraryDiffKind, mesa_line: number | null, disk_line: number | null, text: string, };
