// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`LibraryItem`] is. Six kinds, and the wire value is the exact word
 * Claude Code (or mesa, for `prompt`) uses for the thing — `kebab-case`
 * keeps `claude-md` readable rather than `claude_md`.
 */
export type LibraryKind = "agent" | "skill" | "hook" | "command" | "prompt" | "claude-md";
