// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";

/**
 * The outcome of importing one bundle item. Import is per-item, not
 * all-or-nothing — a failing item is reported here and the rest still
 * apply. (Deliberately the same posture as `LibrarySyncResult`.)
 */
export type LibraryImportResult = { name: string, kind: LibraryKind, scope: LibraryScope, 
/**
 * `created | replaced | skipped | failed`.
 */
status: string, 
/**
 * The db id of the row this item resolved to — the one created,
 * replaced, or left untouched by a `skip`, which is how a caller
 * identifies the row that won a conflict it did not overwrite. Null
 * only for `failed`, where no row was reached at all.
 */
item_id: number | null, error: string | null, };
