// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryHookRegistration } from "./LibraryHookRegistration";

/**
 * Where one `hook` library item stands in its scope's
 * `.claude/settings.json`, and what mesa would write to register it. The
 * same shape answers the read, the register and the unregister, so a caller
 * reads the outcome rather than inferring it.
 */
export type LibraryHookStatus = { 
/**
 * Null for an unshadowed built-in, exactly as on [`LibraryItem`].
 */
item_id: number | null, name: string, 
/**
 * The settings file this item's scope registers into — `$HOME` for
 * `user`, the project's `local_path` for `project`.
 */
settings_path: string, 
/**
 * The command mesa writes when it registers this hook.
 */
command: string, 
/**
 * Derived: true iff `registrations` is non-empty.
 */
registered: boolean, registrations: Array<LibraryHookRegistration>, 
/**
 * `core::library::HOOK_EVENTS`, carried so the editor's event list is
 * the same list the server validates against and cannot drift from it.
 */
events: Array<string>, };
