// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`LibraryItem`] is. Five kinds, and the wire value is the exact word
 * Claude Code (or mesa, for `prompt`) uses for the thing — `kebab-case`
 * keeps `claude-md` readable rather than `claude_md`. The `command` kind
 * mesa task 919 shipped was folded into `prompt` by mesa task 1139; the one
 * place the old word is still read is a library bundle
 * (`core::library::import`), so an export taken before that change still
 * imports.
 */
export type LibraryKind = "agent" | "skill" | "hook" | "prompt" | "claude-md";
