// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";
import type { LibrarySyncStatus } from "./LibrarySyncStatus";

/**
 * One row of a sync scan — one *path*, comparing the mesa side to the disk
 * side. `item_id`/`builtin_id` are both null only for a `disk-new` row (a
 * file with no mesa row at all).
 */
export type LibrarySyncRow = { item_id: number | null, builtin_id: string | null, name: string, kind: LibraryKind, scope: LibraryScope, project_id: number | null, path: string, status: LibrarySyncStatus, mesa_body: string | null, disk_body: string | null, baseline: string | null, };
