// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";

/**
 * One library row as it travels between mesa instances.
 */
export type LibraryBundleItem = { name: string, kind: LibraryKind, scope: LibraryScope, 
/**
 * The project's NAME, not its id — ids are machine-local. Present iff
 * `scope` is `project`, resolved back to an id on import via
 * `Store::find_project_by_name`.
 */
project: string | null, body: string, 
/**
 * The built-in this row forked from, so a fork imports as a fork.
 */
builtin_id: string | null, };
