// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side one line of a [`LibrarySyncRow::diff`] belongs to.
 */
export type LibraryDiffKind = "context" | "mesa-only" | "disk-only";
