// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryBundleItem } from "./LibraryBundleItem";

/**
 * A downloadable bundle of a library's contents (`core::library::export`),
 * portable to another mesa instance.
 */
export type LibraryBundle = { 
/**
 * Format version; `1` today. A bundle whose version this mesa does not
 * know is refused whole, not partly applied (`core::library::import`).
 */
version: number, exported_at: string, items: Array<LibraryBundleItem>, };
