// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a [`LibraryItem`] lives: a personal, machine-wide row (the home
 * dir), or one bound to a project (that project's `local_path`).
 */
export type LibraryScope = "user" | "project";
