// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a [`LibraryItem`]'s history. A row is appended only when the
 * body actually changes, so this is a list of distinct contents, not a list
 * of edits.
 */
export type LibraryVersion = { id: number, item_id: number, body: string, 
/**
 * Who wrote this body: `edit` (the item was saved in mesa) or
 * `sync-pull` (the disk side won a sync and was pulled in).
 */
source: string, created_at: string, };
