// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryDiffLine } from "./LibraryDiffLine";
import type { LibraryImportStatus } from "./LibraryImportStatus";
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";

/**
 * One row of an import preview — one bundle item, against the row this
 * instance would actually resolve it to. Computed server-side rather than
 * guessed at in the browser because the matching rule is import's own
 * (`(kind, scope, project, name)`, then the `builtin_id`'s existing fork),
 * and a preview that matched differently would be a preview of something
 * else. Writes nothing.
 */
export type LibraryImportRow = { name: string, kind: LibraryKind, scope: LibraryScope, 
/**
 * The project's NAME, as the bundle item carries it.
 */
project: string | null, status: LibraryImportStatus, 
/**
 * The db id of the row this item resolved to, null when none did.
 */
item_id: number | null, 
/**
 * The existing row's body — null when nothing was resolved.
 */
local_body: string | null, bundle_body: string, 
/**
 * When the local row last changed — the newest
 * `library_versions.created_at` when it has any history, else its
 * `updated_at`, exactly as [`LibrarySyncRow::mesa_updated_at`] is read.
 * The imported side's own date is the bundle's `exported_at`, which is
 * bundle-level and therefore not repeated on every row.
 */
local_updated_at: string | null, 
/**
 * The line-level local-vs-bundle diff, `Some` only for `conflict` —
 * [`LibrarySyncRow::diff`]'s own rule, both sides existing and
 * differing. The diff's "mesa" side is the local row, its "disk" side
 * the bundle.
 */
diff: Array<LibraryDiffLine> | null, 
/**
 * Why this item could not even be matched (an unknown project name, a
 * scope/project pairing the bundle got wrong) — the same failure
 * `import` would report as `status: "failed"`. Non-null for exactly the
 * `unresolvable` status, which is the one that says *that* it cannot
 * resolve; this says why.
 */
error: string | null, };
