// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryKind } from "./LibraryKind";
import type { LibraryScope } from "./LibraryScope";

/**
 * One library record — an agent definition, a skill, a hook script, a slash
 * command, the live-conversation prompt, or a CLAUDE.md, stored in mesa and
 * (for every kind but `prompt`) synced against a file on disk.
 *
 * `id` is `null` for an unshadowed built-in (`core::library::BUILTINS`) —
 * there is no db row yet, `builtin` is `true`, and `builtin_id` names which
 * built-in it is. Editing a built-in forks it: a db row appears carrying
 * `builtin_id`, `builtin` becomes `false`, and `id` becomes real.
 */
export type LibraryItem = { id: number | null, 
/**
 * `^[A-Za-z0-9][A-Za-z0-9._-]*$`, no `/`, no `..` — half of a filename.
 */
name: string, kind: LibraryKind, scope: LibraryScope, 
/**
 * Required iff `scope` is `project`, and must be null iff `scope` is
 * `user` — the same pairing rule `TaskPatch`'s neighbours enforce.
 */
project_id: number | null, 
/**
 * The file's contents. May be empty.
 */
body: string, 
/**
 * The built-in this row forked from, or null for a purely user-authored
 * row. Unique when set — a built-in forks at most once.
 */
builtin_id: string | null, 
/**
 * Derived, never stored: true iff this row has no db id (an unshadowed
 * built-in reported in its place).
 */
builtin: boolean, 
/**
 * Derived from `kind`/`scope`/`name` via `core::library::relative_path`;
 * null for `prompt`, which has no file.
 */
path: string | null, 
/**
 * The last body mesa and the file on disk agreed on — the sync
 * baseline. Null until the first sync.
 */
synced_body: string | null, synced_at: string | null, created_at: string | null, updated_at: string | null, };
