// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who said one turn. `user` is dictated text the *person* typed or spoke into
 * the page; `mesa` is what the agent sends back, which is what gets spoken.
 * The pair is the whole vocabulary — a live session is two-sided.
 */
export type LiveRole = "user" | "mesa";
