// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The physical browser window a live conversation is being held in, as the
 * page reports it (mesa task 895): `window.screenX`/`screenY` and
 * `outerWidth`/`outerHeight`, rounded to whole pixels.
 *
 * It exists because the agent otherwise has no way to *see* the screen. A
 * route says which page, a [`LiveContext`] says what is open on it, and
 * neither says what actually rendered — so `mesa live look` screenshots the
 * window, and this box is how it finds the right one. The desktop tooling
 * mesa asks (`loki`) reports every window's frame in the same screen
 * coordinates, and a window's position and size together are its identity:
 * several headless browsers on this machine are titled `mesa`, so matching on
 * a title would photograph one of them, while only the browser that is
 * actually joined to the conversation ever reports a box.
 *
 * Reported by the page, so it needs a TS type — unlike the shot itself, which
 * no browser ever sees.
 */
export type LiveWindow = { x: number, y: number, width: number, height: number, };
