// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveContextKind } from "./LiveContextKind";

/**
 * What the person is actually looking at, as reported by the page alongside
 * the route (mesa task 888).
 *
 * A route says which URL the browser is at; it does not say which file is
 * open in the editor, which diagram is on the canvas, or which commit is
 * selected in the history. This is that second half, and it is a **small
 * fixed shape** rather than a free-form blob so the agent can say something
 * useful about it without parsing anything: `kind` is the page, `id` is the
 * identity of the thing in focus (a file path, a diagram id, a task id, a
 * commit sha), `label` is the human — and therefore *spoken* — name for it,
 * and `detail` is whatever extra the page has (a line number, a selected
 * frame, a mode).
 *
 * Every field but `kind` is optional, and absent genuinely means "nothing
 * selected": a page with an empty editor reports its kind and no more, rather
 * than an empty string the agent would have to treat as a name.
 */
export type LiveContext = { kind: LiveContextKind, id: string | null, label: string | null, detail: string | null, };
