// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveNotebookEntry } from "./LiveNotebookEntry";

/**
 * What a notebook write — `add`, `replace` or `merge`, on the CLI and over
 * `POST`/`PATCH /api/live/memory` — answers (mesa task 1331): the entry
 * written, **flattened**, so every key a plain [`LiveNotebookEntry`] carries
 * stays at the top level where callers already read it, plus `evicted` —
 * the entries the write retired as `evicted` to bring the notebook back
 * within its word budget, least recently used first, each the full retired
 * record. Empty when the write fitted.
 */
export type LiveNotebookWrite = { evicted: Array<LiveNotebookEntry>, id: number, 
/**
 * The bullet itself. Untrusted: it is written by an agent reading
 * dictated speech, so `live::agent_prompt` appends it as data, never as an
 * instruction. Bounded by `live::LIVE_NOTEBOOK_ENTRY_MAX` characters.
 */
body: string, created_at: string, updated_at: string, 
/**
 * The conversation that wrote it (`ON DELETE SET NULL`), or the newest
 * one at the time when it was added from the UI between conversations.
 */
source_session_id: number | null, 
/**
 * The conversation that last relied on it (`mesa live memory touch`, or a
 * replace), which is what retirement candidacy is measured from.
 */
last_used_session_id: number | null, retired_at: string | null, 
/**
 * `decayed` (old rows only) | `evicted` | `deleted` | `replaced` |
 * `merged`, null while the entry is active.
 */
retired_reason: string | null, 
/**
 * For a `merged` retirement, the entry this one was folded into
 * (`Store::merge_notebook_entries`); null otherwise. Bounded, so it
 * stays in the `--quiet` shape.
 */
merged_into: number | null, 
/**
 * The project whose notebook this is (mesa task 1333, `naru memory`);
 * null for the live, project-agnostic notebook. Bounded, kept by
 * `--quiet`.
 */
project_id: number | null, 
/**
 * When a project entry was last touched, replaced or moved in — the
 * clock a project notebook evicts on. Always null in the live notebook,
 * which measures use in sessions (`last_used_session_id`).
 */
last_used_at: string | null, };
