// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A side effect a `mesa` turn asks the *page* to perform, beside speaking.
 * One value, deliberately: driving the browser somewhere is the one thing the
 * conversation needs the page for, and a second verb would be a second
 * vocabulary to keep in sync with the frontend router.
 */
export type LiveAction = "navigate";
