// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the live **notebook** (mesa task 1147): a bullet earlier
 * conversations left for later ones — a preference, a working norm, the
 * reason behind a decision, a pointer to a task id. The whole active
 * notebook rides in every live agent's prompt (`live::agent_prompt`), so it
 * is **budgeted** (`live::LIVE_NOTEBOOK_BUDGET_WORDS`) and edited one entry
 * at a time, never rewritten whole.
 *
 * Retiring is a **soft delete**: the row stays (and stays searchable in the
 * archive, `Store::search_live_memory`) with `retired_at`/`retired_reason`
 * stamped, and drops out of the prompt and the default list. `decayed` is the
 * automatic kind — an entry no conversation has used for
 * `live::LIVE_NOTEBOOK_DECAY_SESSIONS` ended sessions — `deleted` an explicit
 * one, `merged` a source folded into another row by a dream pass (mesa task
 * 1152, `merged_into` naming the row that replaced it), and `replaced` is
 * reserved for a future rewrite-as-new-row path (a replace today updates the
 * row in place, keeping its provenance). Any retirement is undone by
 * `Store::restore_notebook_entry`.
 *
 * ts-exported: the Settings page's Memory tab lists and edits these over
 * `/api/live/memory`. Its sibling [`LiveMemoryHit`] is not — search is
 * CLI-only.
 */
export type LiveNotebookEntry = { id: number, 
/**
 * The bullet itself. Untrusted: it is written by an agent reading
 * dictated speech, so `live::agent_prompt` appends it as data, never as an
 * instruction. Bounded by `live::LIVE_NOTEBOOK_ENTRY_MAX` characters.
 */
body: string, created_at: string, updated_at: string, 
/**
 * The conversation that wrote it (`ON DELETE SET NULL`), or the newest
 * one at the time when it was added from the UI between conversations.
 */
source_session_id: number | null, 
/**
 * The conversation that last relied on it (`mesa live memory touch`, or a
 * replace), which is what decay is measured from.
 */
last_used_session_id: number | null, retired_at: string | null, 
/**
 * `decayed` | `deleted` | `replaced` | `merged`, null while the entry is
 * active.
 */
retired_reason: string | null, 
/**
 * For a `merged` retirement, the entry this one was folded into
 * (`Store::merge_notebook_entries`); null otherwise. Bounded, so it
 * stays in the `--quiet` shape.
 */
merged_into: number | null, };
