// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a `mesa` turn is mesa's own status report about the agent rather than
 * the agent's words (mesa task 1157). The agent cannot report its own
 * blocked state — a `claude --bg` session stuck on a permission prompt says
 * nothing, and so does one that has simply gone quiet — so detection is
 * external, and the report is written *as a turn* so it is spoken and shown
 * exactly once, the `played_at` rule, like anything else mesa says. One
 * kind: `permission` (the job is `blocked` on a prompt in `claude agents`).
 * A second, `stalled`, was removed by mesa task 1218 and its rows cleared
 * by migration. Null on every turn the agent or the person actually said.
 */
export type LiveNotice = "permission";
