// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one live **board** holds — the four things a picture can be in a
 * spoken conversation (mesa task 1071). The kind decides what `body` is and
 * how `GET /api/live/boards/{id}/render` serves it, and it is fixed at push
 * time: a board is a snapshot, so there is nothing to convert later.
 *
 * - `markdown` — markdown source, rendered by the page's own `<Markdown>`.
 * - `html` — a whole HTML document, framed in a sandboxed `<iframe>` behind
 *   the same CSP an artifact is rendered under.
 * - `diagram` — SVG markup, rendered from a mesa diagram *at push time*
 *   (`core::board::diagram_svg`), which is what makes it a snapshot rather
 *   than a live view of a canvas that may have moved on since.
 * - `image` — base64 of a file's bytes, so a board is self-contained: no
 *   filesystem dependency after the push, no traversal surface on the read,
 *   and `keep --task` writes the bytes straight into an attachment.
 */
export type LiveBoardKind = "markdown" | "html" | "diagram" | "image";
