// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a live conversation is still running. Exactly two states: it is
 * running, or it is over. There is no "paused" — a conversation the user
 * stopped is ended, and going live again starts a new session with its own
 * transcript.
 */
export type LiveStatus = "live" | "ended";
