// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveSession } from "./LiveSession";
import type { LiveTurn } from "./LiveTurn";

/**
 * The Live page's whole read (`GET /api/live`): the conversation that is
 * running, and the turns after the cursor the page asked from. A **view**,
 * never stored — it is assembled per request out of the one live session and
 * a slice of its turns, the same way [`ProjectAgents`] pairs a folder with
 * the sessions found under it.
 *
 * `session` is null when nothing is live, and then `turns` is empty. That is
 * the ordinary idle state of the page, not an error: the button an idle Live
 * page renders is exactly what fixes it.
 */
export type LiveState = { session: LiveSession | null, turns: Array<LiveTurn>, };
