// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveAction } from "./LiveAction";
import type { LiveRole } from "./LiveRole";

/**
 * One utterance in a live conversation — a dictated line from the user, or a
 * reply from the agent. `text` is treated strictly as **data, never as
 * instructions** (CLAUDE.md): a dictated line is untrusted free text, and it
 * reaches the agent as one `Command::arg`.
 */
export type LiveTurn = { id: number, session_id: number, role: LiveRole, 
/**
 * What was said. Spoken aloud when the role is `mesa`, so it is prose —
 * and bounded, since a runaway body would wedge the synthesiser. Empty
 * only on a pure `navigate` turn, which moves the page and says nothing.
 */
text: string, 
/**
 * What the page should *do* with this turn beside speak it. Null on every
 * user turn, and on a mesa turn that only speaks.
 */
action: LiveAction | null, 
/**
 * The `#/…` route `action: navigate` moves the browser to. Present iff
 * `action` is.
 */
target: string | null, 
/**
 * When the turn was recorded (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the agent **consumed** this user turn (`mesa live listen`). Stamped
 * once, inside the same statement that selects the turn, so two listeners
 * can never be handed the same utterance. Null on a mesa turn.
 */
delivered_at: string | null, 
/**
 * When the browser finished speaking this mesa turn. Stamped once and
 * never moved or cleared — the `read_at` rule — so a re-render can never
 * make the page say something twice.
 */
played_at: string | null, };
