// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveStatus } from "./LiveStatus";

/**
 * One live conversation. **At most one is `live` at a time** (`Store`
 * enforces it): the page has one microphone-shaped text field and one
 * `<audio>` element, so a second concurrent conversation would have nowhere
 * to be heard.
 */
export type LiveSession = { id: number, 
/**
 * The project the conversation is about, or null for an unscoped one. The
 * FK is `ON DELETE SET NULL` (the call the inbox makes): a conversation
 * outlives the project row it mentioned.
 */
project_id: number | null, 
/**
 * The spawn receipt from `agents::spawn_bg` — the Claude session driving
 * this conversation, when the spawn printed one. Null when the session
 * was started with no agent, or when the command printed no receipt.
 */
agent_id: string | null, status: LiveStatus, 
/**
 * Where the user's browser currently is (a `#/…` hash route), as last
 * reported by the page. The agent reads it to know what the user is
 * looking at; it is never authority for anything mesa does.
 */
route: string | null, 
/**
 * When the conversation started (SQLite `datetime` text, UTC).
 */
started_at: string, 
/**
 * When the session row was last written — bound to an agent, re-routed,
 * or ended. A turn is its own row and does not move this.
 */
updated_at: string, 
/**
 * When the conversation ended, or null while it is live.
 */
ended_at: string | null, };
