// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/version`: the running binary's own version
 * (`CARGO_PKG_VERSION`), shown under the wordmark in the app header.
 * Unrelated to `ProjectVersion` above, which reads a *project's* manifest.
 */
export type MesaVersion = { version: string, };
