// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model family's rates, USD per **1M tokens**. All four are explicit —
 * mesa never derives a cache rate from the input rate, because the
 * relationship is a pricing convention, not arithmetic mesa gets to assume.
 */
export type ModelRates = { input: number, output: number, cache_read: number, cache_write: number, };
