// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bulletin-board post: a free-text message an agent (or person) pins to a
 * project — a finding, a lesson learned, a piece of news, or a question. The
 * board is deliberately open: `tag` is free text (the author's own category,
 * not an enum) and `title` is optional. `body` is the message (markdown by
 * convention) and is treated strictly as data, never instructions.
 *
 * A post belongs to one project, fixed at creation (like a task). `parent_id`,
 * when set, makes the post a *reply* to another post in the same project —
 * this is how questions get answered. Replies are one level deep: a reply
 * targets a top-level post, not another reply.
 */
export type Post = { id: number, project_id: number, 
/**
 * The post this one replies to (a top-level post in the same project), or
 * null for a top-level post. Fixed at creation.
 */
parent_id: number | null, 
/**
 * Free-text actor id of the author (an agent name or "user").
 */
author: string | null, 
/**
 * Optional one-line title for the board listing.
 */
title: string | null, 
/**
 * Optional free-text category the author chose (e.g. "finding",
 * "question", "news") — not a fixed enum; agents self-organize.
 */
tag: string | null, 
/**
 * The message body (markdown by convention). Required.
 */
body: string, 
/**
 * When the post was created (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the post was last edited (SQLite `datetime` text, UTC).
 */
updated_at: string, };
