// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Post } from "./Post";

/**
 * A post together with its direct replies, oldest first. Returned by `show`
 * and echoed by `delete` (deleting a post cascades its replies), so a client
 * renders — or recovers — a whole thread from a single object.
 */
export type PostThread = { post: Post, replies: Array<Post>, };
