// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact post object for `list` responses: the full post minus `body` and
 * `parent_id` (the list shows only top-level posts), plus a derived
 * `reply_count` so a client sees which threads have answers without a `show`.
 */
export type PostSummary = { id: number, project_id: number, author: string | null, title: string | null, tag: string | null, 
/**
 * Derived: number of direct replies to this post.
 */
reply_count: number, created_at: string, updated_at: string, };
