// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { 
/**
 * ids are SQLite rowids, well within JS safe-integer range, so they are
 * exported as `number` rather than ts-rs's default `bigint` for i64.
 */
id: number, name: string, description: string | null, 
/**
 * Root (first) commit hash of the source repo this project tracks, if any.
 * Stable across clones/worktrees/moved folders, so every checkout of the
 * same source resolves to one project. Set at create time or via update;
 * unique across projects (a commit binds to exactly one project).
 */
root_commit: string | null, 
/**
 * Last-known working folder of this project on this machine (the repo
 * toplevel). Machine-local convenience, not identity (that is
 * `root_commit`): it anchors the Agents surface — which Claude Code
 * sessions belong here, and where new ones start. Auto-learned on
 * `project create` and refreshed by `project resolve`.
 */
local_path: string | null, 
/**
 * Hides the project from unscoped views (project list, unscoped task
 * list/next, sidebar main list) without deleting anything. Flipped via
 * `Store::archive_project` / `unarchive_project`; every query scoped to
 * an explicit project id/name is unaffected.
 */
archived: boolean, 
/**
 * Manual list position (task 666), the project-level twin of
 * `Task::sort_order`: `Store::list_projects` orders by it, so the CLI,
 * the API and the left nav all render one agreed order. Fractional —
 * a drag writes the midpoint between its new neighbours rather than
 * renumbering the list, so one drag is one write. Backfilled from `id`,
 * so an un-dragged install is still in creation order.
 */
sort_order: number, };
