// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCommit } from "./GitCommit";

/**
 * `GET /api/projects/{id}/git/log` response. Mirrors ProjectGitView's
 * empty-state ladder, one level deeper: path null = no local_path; path
 * set + commits null = folder gone / not a git repo; path set + commits
 * = Some([]) = a real repo with zero commits (unborn HEAD). Never an error.
 */
export type ProjectGitLog = { path: string | null, commits: Array<GitCommit> | null, };
