// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRepoView } from "./GitRepoView";

/**
 * `GET /api/projects/{id}/git` response. Mirrors ProjectAgents' empty-state
 * pattern: path null = no local_path; path set + repo null = folder gone
 * or not a git repo. Never an error.
 */
export type ProjectGitView = { path: string | null, repo: GitRepoView | null, };
