// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeEntry } from "./FileTreeEntry";

/**
 * `GET /api/projects/{id}/files` response. Ladder mirrors `ProjectGitView`:
 * path null = no local_path; path set + tree null = dead/unreadable folder;
 * path set + tree = Some(_) = live folder (root itself always readable at
 * that point, so this is never Some(vec![]) representing "unreadable" — an
 * unreadable root collapses to the dead-folder rung, same as git's is_dir
 * check). Never an error.
 */
export type ProjectFileTree = { path: string | null, tree: Array<FileTreeEntry> | null, 
/**
 * True iff MAX_TREE_ENTRIES or MAX_TREE_DEPTH was hit anywhere during
 * the walk (one global flag, not per-node — good enough to tell the UI
 * "this repo is bigger than what you're seeing").
 */
truncated: boolean, };
