// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSession } from "./AgentSession";

/**
 * The Agents view for one project: the folder sessions are matched under
 * (the project's `local_path`) and the live sessions running there. `path`
 * is null when the project has no `local_path` — then `agents` is empty and
 * the UI explains how to link a folder.
 */
export type ProjectAgents = { path: string | null, agents: Array<AgentSession>, };
