// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRepoView } from "./GitRepoView";
import type { GitWorktree } from "./GitWorktree";

/**
 * `GET /api/projects/{id}/git` response. Mirrors ProjectAgents' empty-state
 * pattern: path null = no local_path; path set + repo null = folder gone
 * or not a git repo. Never an error.
 */
export type ProjectGitView = { path: string | null, repo: GitRepoView | null, 
/**
 * All worktrees of this repo (from `local_path`, regardless of which
 * one `repo` currently reflects — see `?worktree=` on this route).
 * None alongside `repo: None` (no repo to list worktrees of).
 */
worktrees: Array<GitWorktree> | null, };
