// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{id}/version`: the version of the app in a project's
 * `local_path`, read out of its package manifest (`core::version`). Derived
 * on every read, never stored. Both fields are `None` — the quiet empty
 * shape, never an error — when there is no folder or no usable manifest.
 */
export type ProjectVersion = { version: string | null, 
/**
 * The bare manifest filename the version came from, e.g. "Cargo.toml".
 */
source: string | null, };
