// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { 
/**
 * ids are SQLite rowids, well within JS safe-integer range, so they are
 * exported as `number` rather than ts-rs's default `bigint` for i64.
 */
id: number, name: string, description: string | null, };
