// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitStatus } from "./GitStatus";

/**
 * One row of `GET /api/git-status`: the status of one project's
 * `local_path`. Projects without a live repo folder are omitted.
 */
export type ProjectGitStatus = { project_id: number, git: GitStatus, };
