// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchFile } from "./FileSearchFile";

/**
 * `GET /api/projects/{id}/files/search?q=` response (mesa task 813, see
 * `core::files::search_files`). Unlike [`ProjectFileTree`] there is no
 * empty-state ladder: no `local_path` / dead folder is 404 `not_found`, the
 * content route's precedent, because a search is a request about a specific
 * root rather than a description of the project's state.
 */
export type ProjectFileSearch = { 
/**
 * Files with at least one hit, in walk order (directories before files,
 * alphabetical within each — [`FileTreeEntry`]'s order, one level at a
 * time, all the way down).
 */
files: Array<FileSearchFile>, 
/**
 * Matches actually returned, across every file — the number the panel's
 * summary states, never an estimate of what is on disk.
 */
total_matches: number, 
/**
 * True iff the walk stopped early: any cap was hit (files, matches, or
 * the number of files opened at all). The panel says so rather than
 * claiming the project holds exactly this many.
 */
truncated: boolean, };
