// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one **detached** script run (mesa task 1224) — the run the
 * Scripts page starts and can walk away from. Four values, deliberately the
 * vocabulary the run pane already renders: a nonzero exit is `Finished` (a
 * nonzero exit is *data* on this surface), `Stopped` is the explicit stop,
 * and `Failed` is "no exit status could be collected" — the stream ended
 * without one, or a server restart abandoned the run — with
 * [`ScriptRunRecord::note`] saying which.
 */
export type ScriptRunStatus = "running" | "finished" | "stopped" | "failed";
