// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptStream } from "./ScriptStream";

/**
 * One line of `POST /api/scripts/{id}/run/stream`'s NDJSON body (mesa task
 * 1196): every output line as it arrives, stdout and stderr interleaved in
 * arrival order, then exactly one `exit` — or one `error` if the run could
 * not be collected after the response had started. Like [`ScriptRun`], never
 * persisted.
 */
export type ScriptRunEvent = { "type": "line", stream: ScriptStream, 
/**
 * Milliseconds since the run started, taken when the line was read.
 */
t: number, 
/**
 * The line without its trailing newline (lossy UTF-8).
 */
text: string, } | { "type": "exit", 
/**
 * Process exit code; -1 when the script was killed by a signal.
 */
code: number, duration_ms: number, 
/**
 * True when either stream passed the 64 KiB cap; that stream's later
 * lines were dropped.
 */
truncated: boolean, } | { "type": "error", message: string, };
