// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of a script's two output pipes a streamed line came from.
 */
export type ScriptStream = "stdout" | "stderr";
