// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptRunStatus } from "./ScriptRunStatus";

/**
 * One **persisted** script run — the record of a detached run, started by
 * `POST /api/scripts/{id}/run/detach` and outliving the tab that started it
 * (mesa task 1224). The two older run routes are unchanged and still persist
 * nothing; this is the third shape, and the only one with a row.
 *
 * It deliberately carries **no `events` field**. The log stays a wire-only
 * concept — the same [`ScriptRunEvent`] NDJSON a live run emits, reached only
 * through `GET /api/script-runs/{id}/stream`, which replays the stored bytes
 * and then follows. That is what lets `list` and `show` return this one type:
 * twenty runs × 64 KiB of log would be unusable in a list, and a second
 * "summary" projection is exactly what this repo does not do.
 */
export type ScriptRunRecord = { id: number, script_id: number, 
/**
 * The values this run was given, keyed by declared arg name — what the
 * form is restored from when the run is reopened. Stored, not derived:
 * the script's declared args may have changed since.
 */
values: Record<string, string>, status: ScriptRunStatus, 
/**
 * The process exit code, once there is one. Null while `running` and for
 * every run that ended without one (`stopped`, `failed`).
 */
exit_code: number | null, 
/**
 * Why there is no exit code — the stop, the collection failure, the
 * server restart. Null on a run that exited normally.
 */
note: string | null, 
/**
 * True when either stream hit the 64 KiB cap, exactly as on a live run's
 * exit event.
 */
truncated: boolean, 
/**
 * The directory the run was started in, resolved server-side at start
 * time. Stored rather than re-derived: the project could be rebound, or
 * its `local_path` changed, between the run and the reopen.
 */
cwd: string | null, started_at: string, ended_at: string | null, };
