// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of value a [`ScriptArg`] accepts. Exactly four kinds — the form
 * renders one control per kind and the run path validates against it, so a
 * fifth kind is a change to both surfaces, never a free addition here.
 */
export type ScriptArgKind = "text" | "number" | "bool" | "choice";
