// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The captured outcome of one script run — the [`HookRun`] twin. A nonzero
 * `exit_code` is the script's own result, not a transport failure: the CLI
 * exits 0 and the API returns 200 with this object either way. Runs are not
 * persisted; this is a request/response record.
 */
export type ScriptRun = { script_id: number, 
/**
 * Process exit code; -1 when the script was killed by a signal.
 */
exit_code: number, 
/**
 * Captured stdout, truncated to 64 KiB.
 */
stdout: string, 
/**
 * Captured stderr, truncated to 64 KiB.
 */
stderr: string, 
/**
 * True when either stream hit the 64 KiB cap and was cut.
 */
truncated: boolean, };
