// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptArg } from "./ScriptArg";

/**
 * A user-authored shell script stored in mesa, run from the web UI's
 * generated form or from `mesa script run`.
 */
export type Script = { id: number, 
/**
 * The project this script belongs to, or null for a global script. Also
 * the run's working directory (the project's `local_path`; `$HOME` when
 * null). Deleting the project un-binds rather than destroys the script —
 * the FK is `ON DELETE SET NULL`, as the inbox's is.
 */
project_id: number | null, 
/**
 * Unique (case-insensitively), non-empty: the CLI resolves a script by id
 * **or** name.
 */
name: string, description: string | null, 
/**
 * The shell source, handed to `bash -c` verbatim. Required, non-empty.
 */
body: string, 
/**
 * Declared arguments, in the order they reach the body as `$1`, `$2`, …
 */
args: Array<ScriptArg>, created_at: string, updated_at: string, };
