// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptArgKind } from "./ScriptArgKind";

/**
 * One declared argument of a [`Script`]. Every value crossing into the shell
 * is a string: `Number` and `Bool` describe the *control* and the validation,
 * not a parsed Rust type, so a half-typed value survives a keystroke in the
 * form and the run path has exactly one representation to pass along.
 */
export type ScriptArg = { 
/**
 * Identifier: `^[A-Za-z_][A-Za-z0-9_-]*$`, ≤64 chars, unique within the
 * script. Constrained because it becomes an `MESA_ARG_*` env-var suffix.
 */
name: string, 
/**
 * Human label for the form; the `name` is used when absent.
 */
label: string | null, kind: ScriptArgKind, required: boolean, 
/**
 * Fills in for an absent optional argument at run time.
 */
default: string | null, 
/**
 * Required and non-empty for `Choice`, and `None` for every other kind.
 */
choices: Array<string> | null, };
