// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a storyboard's append-only change history. `actor` is the
 * free-text id of whoever made the change (an agent name or "user"); it is the
 * collaboration record — who did what, when. `action` is a stable machine
 * token (e.g. `frame_added`, `frame_moved`, `edge_added`); `summary` is a
 * human-readable one-liner for the web history view.
 */
export type StoryboardEvent = { id: number, storyboard_id: number, actor: string | null, action: string, summary: string, 
/**
 * When the change happened (SQLite `datetime` text, UTC).
 */
at: string, };
