// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";
import type { FrameEdge } from "./FrameEdge";
import type { Storyboard } from "./Storyboard";

/**
 * The full contents of one storyboard: the board plus all of its frames and
 * edges. Returned by `show` and echoed by `delete`, so a client renders (or
 * recovers) an entire canvas from a single object.
 */
export type StoryboardView = { storyboard: Storyboard, frames: Array<Frame>, edges: Array<FrameEdge>, };
