// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";

/**
 * `GET /api/system` and `mesa system`: a live reading of the host the mesa
 * server is running on (`core::system`). Derived on every read, never
 * stored — mesa keeps no history of it.
 *
 * Every field a platform may decline to report is `Option`, and `None` means
 * **this host did not say**, never zero: a `null` and a reading of `0` are
 * different facts and the UI must not draw them the same way.
 */
export type SystemInfo = { ram_total_bytes: number, ram_used_bytes: number, swap_total_bytes: number, swap_used_bytes: number, 
/**
 * The first CPU's brand string, e.g. "Apple M1 Pro".
 */
cpu_model: string | null, 
/**
 * Physical cores; `None` where the platform will not say.
 */
cpu_cores: number | null, 
/**
 * Logical cores (hardware threads) — always known, since it is the
 * length of the per-core list below.
 */
cpu_logical: number, 
/**
 * Overall utilisation, 0–100, across the whole sampling window.
 */
cpu_usage_pct: number, 
/**
 * Per logical core, in `cpu_logical` order.
 */
cpu_per_core_pct: Array<number>, 
/**
 * 1/5/15-minute load average; `None` where the platform has no such
 * idea (Windows), rather than three misleading zeroes.
 */
load_average: [number, number, number] | null, gpu: GpuInfo | null, uptime_secs: number, 
/**
 * The volume holding mesa's own database — not the whole machine's
 * storage, since that is the one disk a mesa user can fill.
 */
disk_total_bytes: number | null, disk_free_bytes: number | null, 
/**
 * Resident set size of the mesa process itself.
 */
process_rss_bytes: number | null, os: string | null, hostname: string | null, };
