// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";
import type { Status } from "./Status";

export type Task = { id: number, project_id: number, parent_id: number | null, title: string, description: string | null, status: Status, priority: Priority, tags: Array<string>, 
/**
 * Definition-of-done for this task; free text, unstructured.
 */
acceptance: string | null, 
/**
 * Free-text receipt of completed work (commit SHA / PR URL / path).
 */
artifact: string | null, 
/**
 * Free-text final summary the agent writes when the task is done;
 * unlike `artifact` (a pointer), this holds the narrative itself.
 */
result: string | null, 
/**
 * When the task row was inserted (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the task row was last updated (SQLite `datetime` text, UTC).
 */
updated_at: string, 
/**
 * Manual board order (spec 328): compared across the whole table (not
 * per-status), so a task keeps its relative position when its status
 * changes. Not a dense rank — a sortable value; ties break on `id`.
 */
sort_order: number, 
/**
 * Derived: true if any dependency is not done/cancelled. Always present.
 */
blocked: boolean, };
