// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

/**
 * An append-only record of a task's status change. `from_status` is null for
 * the row written when the task is created.
 */
export type TaskEvent = { id: number, task_id: number, from_status: Status | null, to_status: Status, 
/**
 * When the change happened (SQLite `datetime` text, UTC).
 */
at: string, };
