// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";
import type { Status } from "./Status";

export type Task = { id: number, project_id: number, parent_id: number | null, title: string, description: string | null, status: Status, priority: Priority, tags: Array<string>, 
/**
 * Definition-of-done for this task; free text, unstructured.
 */
acceptance: string | null, 
/**
 * Free-text receipt of completed work (commit SHA / PR URL / path).
 */
artifact: string | null, 
/**
 * Free-text final summary the agent writes when the task is done;
 * unlike `artifact` (a pointer), this holds the narrative itself.
 */
result: string | null, 
/**
 * When the task row was inserted (SQLite `datetime` text, UTC).
 */
created_at: string, 
/**
 * When the task row was last updated (SQLite `datetime` text, UTC).
 */
updated_at: string, 
/**
 * Manual board order (spec 328): compared across the whole table (not
 * per-status), so a task keeps its relative position when its status
 * changes. Not a dense rank — a sortable value; ties break on `id`.
 */
sort_order: number, 
/**
 * Who currently holds the task (task 563): an opaque caller-supplied
 * identifier — for an agent, its Claude Code session id, so a reader can
 * check liveness out-of-band (`ps aux | grep "claude attach <owner>"`)
 * instead of guessing from `updated_at`. Null when unclaimed; cleared
 * automatically when the task leaves `in_progress`.
 */
owner: string | null, 
/**
 * When the current claim was taken or last renewed (SQLite `datetime`
 * text, UTC). Unlike `updated_at` it moves ONLY on claim/renew, never on
 * an ordinary field write — that is the whole point of the pair.
 */
claimed_at: string | null, 
/**
 * Derived: true if any dependency is not done/cancelled. Always present.
 */
blocked: boolean, };
