// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";
import type { Status } from "./Status";

/**
 * Compact task object for `list` responses (Requirement 6): the full object
 * minus `description`.
 */
export type TaskSummary = { id: number, project_id: number, parent_id: number | null, title: string, status: Status, priority: Priority, tags: Array<string>, 
/**
 * Definition-of-done, surfaced in `list` so agents see it without `show`.
 */
acceptance: string | null, 
/**
 * Manual board order (spec 328); see `Task::sort_order`.
 */
sort_order: number, blocked: boolean, };
