// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";
import type { Status } from "./Status";

export type Task = { id: number, project_id: number, parent_id: number | null, title: string, description: string | null, status: Status, priority: Priority, tags: Array<string>, 
/**
 * Derived: true if any dependency is not done/cancelled. Always present.
 */
blocked: boolean, };
