// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An absolute canvas-coordinate routing anchor on a `FrameEdge` — same
 * coordinate space as `Frame.x/y`, not relative to either endpoint frame.
 */
export type Waypoint = { x: number, y: number, };
